///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace Finetuned
{
    /// <summary>
    /// The login recording.
    /// </summary>
    [TestModule("c96eb5cb-a88c-4ef0-8433-896e1f0bcfac", ModuleType.Recording, 1)]
    public partial class login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the project1Repository repository.
        /// </summary>
        public static project1Repository repo = project1Repository.Instance;

        static login instance = new login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 60;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 5.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.ContainerPanel.ButtonLogout' at 40;11.", repo.WebDocumentIceFish.ContainerPanel.ButtonLogoutInfo, new RecordItemIndex(0));
            repo.WebDocumentIceFish.ContainerPanel.ButtonLogout.Click("40;11");
            Delay.Milliseconds(2240);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.ContainerPanel.TextTextInput' at 88;5.", repo.WebDocumentIceFish.ContainerPanel.TextTextInputInfo, new RecordItemIndex(1));
            repo.WebDocumentIceFish.ContainerPanel.TextTextInput.Click("88;5");
            Delay.Milliseconds(870);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'icefish'.", new RecordItemIndex(2));
            Keyboard.Press("icefish");
            Delay.Milliseconds(2330);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.ContainerPanel.TextTextInput1' at 70;10.", repo.WebDocumentIceFish.ContainerPanel.TextTextInput1Info, new RecordItemIndex(3));
            repo.WebDocumentIceFish.ContainerPanel.TextTextInput1.Click("70;10");
            Delay.Milliseconds(770);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'icefish'.", new RecordItemIndex(4));
            Keyboard.Press("icefish");
            Delay.Milliseconds(3260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.ContainerPanel.ButtonSubmit' at 32;10.", repo.WebDocumentIceFish.ContainerPanel.ButtonSubmitInfo, new RecordItemIndex(5));
            repo.WebDocumentIceFish.ContainerPanel.ButtonSubmit.Click("32;10");
            Delay.Milliseconds(2520);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.ContainerVBox.ButtonNew' at 18;7.", repo.WebDocumentIceFish.ContainerVBox.ButtonNewInfo, new RecordItemIndex(6));
            repo.WebDocumentIceFish.ContainerVBox.ButtonNew.Click("18;7");
            Delay.Milliseconds(790);
            
        }

#region Image Feature Data
#endregion
    }
}
