///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace Finetuned
{
	/// <summary>
	/// The Recording6 recording.
	/// </summary>
	public partial class Recording6
	{


		public static void records6()
		{
	Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_3' at 6;11.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_3.MoveTo("6;11", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(770);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 141;77.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("141;77", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(1510);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonParsers' at 56;8.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonParsers.Click("56;8", 300);
			//Delay.Milliseconds(1740);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_6' at 9;14.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_6.MoveTo("9;14", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(630);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 257;146.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("257;146", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(760);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonFormatters' at 90;11.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonFormatters.Click("90;11", 300);
			//Delay.Milliseconds(1190);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_9' at 4;12.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_9.MoveTo("4;12", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(540);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 366;170.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("366;170", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(1090);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonEndpoints' at 60;7.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonEndpoints.Click("60;7", 300);
			//Delay.Milliseconds(1910);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_15' at 4;11.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_15.MoveTo("4;11", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(980);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 549;155.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("549;155", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(2180);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonRouters' at 85;12.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonRouters.Click("85;12", 300);
			//Delay.Milliseconds(1690);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine' at 15;8.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine.Click("15;8", 300);
			//Delay.Milliseconds(710);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_9238' at 25;33.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_9238.MoveTo("25;33", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(490);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_208107' at 14;24.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_208107.MoveTo("14;24", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(1240);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine' at 15;8.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine.Click("15;8", 300);
			//Delay.Milliseconds(730);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_208107' at 28;17.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_208107.MoveTo("28;17", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(1100);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_317131' at 30;28.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_317131.MoveTo("30;28", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(1120);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine' at 12;7.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine.Click("12;7", 300);
			//Delay.Milliseconds(690);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_317131' at 17;24.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_317131.MoveTo("17;24", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(510);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_15_500116' at 11;29.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_15_500116.MoveTo("11;29", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(1410);
			Report.Info("Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_9238' at 10;19.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_9238.Click(MouseButtons.Right, "10;19", 300);
			//Delay.Milliseconds(730);
			Report.Info("Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 33;13.");
			repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("33;13", 300);
			//Delay.Milliseconds(2680);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 76;7.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("76;7", 300);
			//Delay.Milliseconds(790);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 130;9.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("130;9", 300);
			//Delay.Milliseconds(1120);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextSourcefile' at 60;6.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextSourcefile.Click("60;6", 300);
			//Delay.Milliseconds(520);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 26;8.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("26;8", 300);
			//Delay.Milliseconds(790);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId' at 46;15.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId.Click("46;15", 300);
			//Delay.Milliseconds(630);
			Report.Info("Key sequence 'source'.");
			Keyboard.Press("source", 100);
			//Delay.Milliseconds(2500);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 40;11.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("40;11", 300);
			//Delay.Milliseconds(1100);
			Report.Info("Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_208107' at 22;25.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_208107.Click(MouseButtons.Right, "22;25", 300);
			//Delay.Milliseconds(680);
			Report.Info("Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 20;9.");
			repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("20;9", 300);
			//Delay.Milliseconds(880);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 106;6.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("106;6", 300);
			//Delay.Milliseconds(980);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 107;12.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("107;12", 300);
			//Delay.Milliseconds(2940);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextParserfile' at 48;7.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextParserfile.Click("48;7", 300);
			//Delay.Milliseconds(990);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 35;7.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("35;7", 300);
			//Delay.Milliseconds(2520);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1' at 37;12.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1.Click("37;12", 300);
			//Delay.Milliseconds(880);
			Report.Info("Key sequence 'par'.");
			Keyboard.Press("par", 100);
			//Delay.Milliseconds(1260);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 32;4.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("32;4", 300);
			//Delay.Milliseconds(1070);
			Report.Info("Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_317131' at 21;22.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_317131.Click(MouseButtons.Right, "21;22", 300);
			//Delay.Milliseconds(730);
			Report.Info("Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 19;2.");
			repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("19;2", 300);
			//Delay.Milliseconds(1090);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 107;5.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("107;5", 300);
			//Delay.Milliseconds(820);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 125;9.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("125;9", 300);
			//Delay.Milliseconds(630);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextTagFormater' at 76;5.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextTagFormater.Click("76;5", 300);
			//Delay.Milliseconds(460);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 39;12.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("39;12", 300);
			//Delay.Milliseconds(1320);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1' at 26;10.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1.Click("26;10", 300);
			//Delay.Milliseconds(120);
			Report.Info("Key sequence 'ta'.");
			Keyboard.Press("ta", 100);
			//Delay.Milliseconds(750);
			Report.Info("Key sequence 'gfor'.");
			Keyboard.Press("gfor", 100);
			//Delay.Milliseconds(1490);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 44;7.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("44;7", 300);
			//Delay.Milliseconds(1490);
			Report.Info("Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_15_500116' at 18;26.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_15_500116.Click(MouseButtons.Right, "18;26", 300);
			//Delay.Milliseconds(690);
			Report.Info("Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 20;12.");
			repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("20;12", 300);
			//Delay.Milliseconds(1930);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 58;15.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("58;15", 300);
			//Delay.Milliseconds(690);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 151;14.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("151;14", 300);
			//Delay.Milliseconds(710);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 114;11.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("114;11", 300);
			//Delay.Milliseconds(680);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextTCPendpoint' at 71;7.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextTCPendpoint.Click("71;7", 300);
			//Delay.Milliseconds(980);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 32;13.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("32;13", 300);
			//Delay.Milliseconds(820);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId2' at 70;8.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId2.Click("70;8", 300);
			//Delay.Milliseconds(2680);
			Report.Info("Key sequence 'tcpendp'.");
			Keyboard.Press("tcpendp", 100);
			//Delay.Milliseconds(1220);
			Report.Info("Key sequence 'oint'.");
			Keyboard.Press("oint", 100);
			//Delay.Milliseconds(1420);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 13;10.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("13;10", 300);
			//Delay.Milliseconds(1380);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.TextNameText' at 100;8.");
			repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameText.Click("100;8", 300);
			//Delay.Milliseconds(590);
			Report.Info("Key sequence '{Capital}F{Capital}ile'.");
			Keyboard.Press("{Capital}F{Capital}ile", 100);
			//Delay.Milliseconds(1360);
			Report.Info("Key sequence '{RShiftKey down}_{RShiftKey up}'.");
			Keyboard.Press("{RShiftKey down}_{RShiftKey up}", 100);
			//Delay.Milliseconds(760);
			Report.Info("Key sequence 'tcp'.");
			Keyboard.Press("tcp", 100);
			//Delay.Milliseconds(960);
			Report.Info("Key sequence '{RShiftKey down}_{RShiftKey up}endpoint'.");
			Keyboard.Press("{RShiftKey down}_{RShiftKey up}endpoint", 100);
			//Delay.Milliseconds(2940);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.TextUITextField' at 98;16.");
			repo.WebDocumentLocalhost_8888.ContainerVBox.TextUITextField.Click("98;16", 300);
			//Delay.Milliseconds(660);
			Report.Info("Key sequence 'test'.");
			Keyboard.Press("test", 100);
			//Delay.Milliseconds(1050);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxRecovery' at 9;10.");
			repo.WebDocumentLocalhost_8888.FormForm.CheckBoxRecovery.Click("9;10", 300);
			//Delay.Milliseconds(600);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxPrcsEvntLog' at 5;9.");
			repo.WebDocumentLocalhost_8888.FormForm.CheckBoxPrcsEvntLog.Click("5;9", 300);
			//Delay.Milliseconds(570);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxMsgEvntLog' at 9;12.");
			repo.WebDocumentLocalhost_8888.FormForm.CheckBoxMsgEvntLog.Click("9;12", 300);
			//Delay.Milliseconds(960);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.ButtonSave1' at 30;9.");
			repo.WebDocumentLocalhost_8888.ContainerVBox.ButtonSave1.Click("30;9", 300);
			//Delay.Milliseconds(1490);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK' at 33;9.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK.Click("33;9", 300);
			//Delay.Milliseconds(1070);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.ButtonPublish' at 32;11.");
			repo.WebDocumentLocalhost_8888.ContainerVBox.ButtonPublish.Click("32;11", 300);
			//Delay.Milliseconds(1300);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK1' at 41;1.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK1.Click("41;1", 300);
			//Delay.Milliseconds(820);		
		}

        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

	}
}
