///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace Finetuned
{
	/// <summary>
	/// The Recording7 recording.
	/// </summary>
	public partial class Recording7
	{
	
	
		public static void records7()
		{
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_20' at 6;7.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_20.MoveTo("6;7", 1000);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(0);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 87;63.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("87;63", 1000);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(350);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonParsers' at 49;7.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonParsers.Click("49;7", 1000);
			//Delay.Milliseconds(3600);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_6' at 9;10.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_6.MoveTo("9;10", 1000);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(120);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 217;95.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("217;95", 1000);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(560);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonFormatters' at 74;8.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonFormatters.Click("74;8", 1000);
			//Delay.Milliseconds(600);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_8' at 6;11.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_8.MoveTo("6;11", 1000);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(0);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 341;143.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("341;143", 1000);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(710);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonEndpoints' at 81;13.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonEndpoints.Click("81;13", 1000);
			//Delay.Milliseconds(730);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_1' at 8;16.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_1.MoveTo("8;16", 1000);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(290);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 471;164.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("471;164", 1000);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(280);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonRouters' at 52;10.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonRouters.Click("52;10", 1000);
			//Delay.Milliseconds(480);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine' at 10;5.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine.Click("10;5", 300);
			//Delay.Milliseconds(410);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_20_3824' at 19;26.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_20_3824.MoveTo("19;26", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(510);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_16856' at 11;15.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_16856.MoveTo("11;15", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(1040);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine' at 7;9.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine.Click("7;9", 300);
			//Delay.Milliseconds(590);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_16856' at 23;25.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_16856.MoveTo("23;25", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(990);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_8_292104' at 4;9.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_8_292104.MoveTo("4;9", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(1040);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine' at 13;7.");
			repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureLine.Click("13;7", 300);
			//Delay.Milliseconds(690);
			Report.Info("Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_8_292104' at 18;19.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_8_292104.MoveTo("18;19", 300);
			Mouse.ButtonDown(MouseButtons.Left);
			//Delay.Milliseconds(630);
			Report.Info("Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_422125' at 10;15.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_422125.MoveTo("10;15", 300);
			Mouse.ButtonUp(MouseButtons.Left);
			//Delay.Milliseconds(1900);
			Report.Info("Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_20_3824' at 22;20.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_20_3824.Click(MouseButtons.Right, "22;20", 300);
			//Delay.Milliseconds(690);
			Report.Info("Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 46;12.");
			repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("46;12", 300);
			//Delay.Milliseconds(770);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 89;5.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("89;5", 300);
			//Delay.Milliseconds(1180);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 111;11.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("111;11", 300);
			//Delay.Milliseconds(1800);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextFtpsource' at 61;12.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextFtpsource.Click("61;12", 300);
			//Delay.Milliseconds(1520);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 32;13.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("32;13", 300);
			//Delay.Milliseconds(3270);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId' at 92;9.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId.Click("92;9", 300);
			//Delay.Milliseconds(680);
			Report.Info("Key sequence 'source'.");
			Keyboard.Press("source", 100);
			//Delay.Milliseconds(2490);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 37;8.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("37;8", 300);
			//Delay.Milliseconds(740);
			Report.Info("Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_16856' at 26;26.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_6_16856.Click(MouseButtons.Right, "26;26", 300);
			//Delay.Milliseconds(600);
			Report.Info("Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 26;10.");
			repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("26;10", 300);
			//Delay.Milliseconds(930);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 95;13.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("95;13", 300);
			//Delay.Milliseconds(930);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 90;9.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("90;9", 300);
			//Delay.Milliseconds(910);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextParserfile' at 52;2.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextParserfile.Click("52;2", 300);
			//Delay.Milliseconds(1040);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 30;12.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("30;12", 300);
			//Delay.Milliseconds(840);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1' at 93;10.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1.Click("93;10", 300);
			//Delay.Milliseconds(1400);
			Report.Info("Key sequence 'test'.");
			Keyboard.Press("test", 100);
			//Delay.Milliseconds(2990);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 40;7.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("40;7", 300);
			//Delay.Milliseconds(800);
			Report.Info("Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_8_292104' at 23;24.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_8_292104.Click(MouseButtons.Right, "23;24", 300);
			//Delay.Milliseconds(570);
			Report.Info("Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 31;10.");
			repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("31;10", 300);
			//Delay.Milliseconds(1040);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 51;8.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("51;8", 300);
			//Delay.Milliseconds(940);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 121;9.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("121;9", 300);
			//Delay.Milliseconds(1550);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextDbFormatter' at 78;10.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextDbFormatter.Click("78;10", 300);
			//Delay.Milliseconds(650);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 27;10.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("27;10", 300);
			//Delay.Milliseconds(1090);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId2' at 90;11.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId2.Click("90;11", 300);
			//Delay.Milliseconds(460);
			Report.Info("Key sequence 'dbformat'.");
			Keyboard.Press("dbformat", 100);
			//Delay.Milliseconds(3340);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 40;16.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("40;16", 300);
			//Delay.Milliseconds(910);
			Report.Info("Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_422125' at 15;11.");
			repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_422125.Click(MouseButtons.Right, "15;11", 300);
			//Delay.Milliseconds(540);
			Report.Info("Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 24;10.");
			repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("24;10", 300);
			//Delay.Milliseconds(930);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId3' at 89;13.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId3.Click("89;13", 300);
			//Delay.Milliseconds(380);
			Report.Info("Key sequence 'dest'.");
			Keyboard.Press("dest", 100);
			//Delay.Milliseconds(2280);
			Report.Info("Key sequence 'db'.");
			Keyboard.Press("db", 100);
			//Delay.Milliseconds(2120);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 48;16.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("48;16", 300);
			//Delay.Milliseconds(870);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton' at 160;9.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonButton.Click("160;9", 300);
			//Delay.Milliseconds(3900);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextDbdestination' at 92;0.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextDbdestination.Click("92;0", 300);
			//Delay.Milliseconds(710);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 22;6.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("22;6", 300);
			//Delay.Milliseconds(820);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 30;8.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("30;8", 300);
			//Delay.Milliseconds(1540);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.TextNameText' at 89;10.");
			repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameText.Click("89;10", 300);
			//Delay.Milliseconds(2820);
			Report.Info("Key sequence 'ftp{RShiftKey down}_{RShiftKey up}to'.");
			Keyboard.Press("ftp{RShiftKey down}_{RShiftKey up}to", 100);
			//Delay.Milliseconds(1980);
			Report.Info("Key sequence '{RShiftKey down}_{RShiftKey up}db'.");
			Keyboard.Press("{RShiftKey down}_{RShiftKey up}db", 100);
			//Delay.Milliseconds(1680);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.TextUITextField' at 83;19.");
			repo.WebDocumentLocalhost_8888.ContainerVBox.TextUITextField.Click("83;19", 300);
			//Delay.Milliseconds(70);
			Report.Info("Key sequence 'test'.");
			Keyboard.Press("test", 100);
			//Delay.Milliseconds(1020);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxRecovery' at 5;7.");
			repo.WebDocumentLocalhost_8888.FormForm.CheckBoxRecovery.Click("5;7", 300);
			//Delay.Milliseconds(600);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxPrcsEvntLog' at 5;7.");
			repo.WebDocumentLocalhost_8888.FormForm.CheckBoxPrcsEvntLog.Click("5;7", 300);
			//Delay.Milliseconds(730);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxMsgEvntLog' at 5;7.");
			repo.WebDocumentLocalhost_8888.FormForm.CheckBoxMsgEvntLog.Click("5;7", 300);
			//Delay.Milliseconds(850);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.ButtonSave1' at 18;14.");
			repo.WebDocumentLocalhost_8888.ContainerVBox.ButtonSave1.Click("18;14", 300);
			//Delay.Milliseconds(1260);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK' at 42;18.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK.Click("42;18", 300);
			//Delay.Milliseconds(880);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.ButtonPublish' at 13;16.");
			repo.WebDocumentLocalhost_8888.ContainerVBox.ButtonPublish.Click("13;16", 300);
			//Delay.Milliseconds(1760);
			Report.Info("Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK1' at 31;10.");
			repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK1.Click("31;10", 300);
			//Delay.Milliseconds(900);		
		}

		static Recording7()
		{
			//Your recording specific initialization code goes here.
		}

        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
	}
}
