'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core

Namespace Validation_Creation_templates

	''' <summary>
	''' The Recording1 recording.
	''' </summary>
	Public Partial Class File_Source

		Shared Sub New()
			'Your recording specific initialization code goes here.
		End Sub

Public Shared Property SourceFile As String  
	   Get  
        Return Src_file    
    End Get      
    Set  
        Src_file   = Value   
    End Set 	
End Property
Private Shared Src_file  As String
		Public Shared Sub GetSource_File()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info(Src_file)
			Keyboard.Press(Src_file)
		End Sub		
		
Public Shared Property DestFile As String  
    Get  
        Return Dest_file   
    End Get  
    Set  
        Dest_file  = Value   
    End Set  
End Property  
Private Shared Dest_file  As String
		Public Shared Sub GetDest_File()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info(Dest_file)
			Keyboard.Press(Dest_file)
		End Sub
Public Shared Property Destpattern As String 	
    Get  
        Return fileDestpattern  
    End Get  
    Set  
        fileDestpattern  = Value   
    End Set  
End Property  
Private Shared fileDestpattern  As String 
		Public Shared Sub getDestpattern()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info(fileDestpattern)
			Keyboard.Press(fileDestpattern)
		End Sub		
Public Shared Property Nxtpoll As String 	
    Get  
        Return Nxtpolltime  
    End Get  
    Set  
        Nxtpolltime  = Value   
    End Set  
End Property  
Private Shared Nxtpolltime  As String 
		Public Shared Sub getNxtpolltime()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'getNxtpolltime'.")
			Keyboard.Press(Nxtpolltime)
		End Sub		
Public Shared Property Sourcepattern As String 	
    Get  
        Return file_Sourcepattern  
    End Get  
    Set  
        file_Sourcepattern  = Value   
    End Set  
End Property  
Private Shared file_Sourcepattern  As String 
		Public Shared Sub getSourcepattern()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'getSourcepattern'.")
			Keyboard.Press(file_Sourcepattern)
		End Sub
Public Shared Property filedesttemp As String 	
    Get  
        Return filedesttempname 
    End Get  
    Set  
        filedesttempname  = Value   
    End Set  
End Property 	
Private Shared filedesttempname  As String 
		Public Shared Sub getfiledesttemp()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info(filedesttempname)
			Keyboard.Press(filedesttempname)
		End Sub
	Public Shared Property Sourcetemp As String 	
    Get  
        Return Sourcetempname 
    End Get  
    Set  
        Sourcetempname  = Value   
    End Set  
End Property 	
Private Shared Sourcetempname  As String 
		Public Shared Sub getSourcetemp()
		Report.Info("Key sequence 'Sourcefile'.")
		Keyboard.Press(Sourcetempname)
		End Sub

		Public Shared Sub getSourceLoc_File()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'getSourceLoc_File'.")
			Keyboard.Press("getSourceLoc_File")
		End Sub

		Public Shared Sub getNxtPoll_File()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'next'.")
			Keyboard.Press("next")
		End Sub

		Public Shared Sub Key_Sequence1()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'sourcefilepattern'.")
			Keyboard.Press("sourcefilepattern")
		End Sub

		Public Shared Sub Key_Sequence2()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'sourcefilepattern'.")
			Keyboard.Press("sourcefilepattern")
		End Sub

		Public Shared Sub Key_Sequence3()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'dest'.")
			Keyboard.Press("dest")
		End Sub

		Public Shared Sub Key_Sequence4()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'templ'.")
			Keyboard.Press("templ")
		End Sub

		Public Shared Sub Key_Sequence5()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'file'.")
			Keyboard.Press("file")
		End Sub

		Public Shared Sub Key_Sequence6()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'tempname'.")
			Keyboard.Press("tempname")
		End Sub

		Private Sub Init()
			' Your recording specific initialization code goes here.
		End Sub
	End Class
End Namespace
