/* Generated by Xgen from: E60_baseline on: 2002-02-12 17:59 */
/*******************************************************************************
* 2002 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   EntSLegCrsReq.hxx
*
*  DESCRIPTION: see documentation
*
*******************************************************************************/

#ifndef _ENTSLEGCRSREQ_HXX_
#define _ENTSLEGCRSREQ_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>


/******************************************************************************/

#ifndef _FUT_BSC_ENT_S_LEG_CRS_REQ_REQUEST_T_
#define _FUT_BSC_ENT_S_LEG_CRS_REQ_REQUEST_T_

typedef struct futBscEntSLegCrsReqRequestTag
{
  char buyCod;
  futCntrIdGrpT futCntrIdGrp;
  trdrIdGrpT trdrIdGrp;
  char ordrQty[DRIV_VOLUME_LEN];
} futBscEntSLegCrsReqRequestT, *pFutBscEntSLegCrsReqRequestT;


#endif  /* _FUT_BSC_ENT_S_LEG_CRS_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _FUT_ENT_S_LEG_CRS_REQ_REQUEST_T_
#define _FUT_ENT_S_LEG_CRS_REQ_REQUEST_T_

typedef struct futEntSLegCrsReqRequestTag
{
  dataHeaderT header;
  futBscEntSLegCrsReqRequestT basic;
} futEntSLegCrsReqRequestT, *pFutEntSLegCrsReqRequestT;


#endif  /* _FUT_ENT_S_LEG_CRS_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _FUT_ENT_S_LEG_CRS_REQ_RESPONSE_T_
#define _FUT_ENT_S_LEG_CRS_REQ_RESPONSE_T_

typedef struct futEntSLegCrsReqResponseTag
{
  dataHeaderT header;
} futEntSLegCrsReqResponseT, *pFutEntSLegCrsReqResponseT;


#endif  /* _FUT_ENT_S_LEG_CRS_REQ_RESPONSE_T_ */

/******************************************************************************/

#ifndef _OPT_BSC_ENT_S_LEG_CRS_REQ_REQUEST_T_
#define _OPT_BSC_ENT_S_LEG_CRS_REQ_REQUEST_T_

typedef struct optBscEntSLegCrsReqRequestTag
{
  char buyCod;
  optCntrIdGrpT optCntrIdGrp;
  trdrIdGrpT trdrIdGrp;
  char ordrQty[DRIV_VOLUME_LEN];
} optBscEntSLegCrsReqRequestT, *pOptBscEntSLegCrsReqRequestT;


#endif  /* _OPT_BSC_ENT_S_LEG_CRS_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _OPT_ENT_S_LEG_CRS_REQ_REQUEST_T_
#define _OPT_ENT_S_LEG_CRS_REQ_REQUEST_T_

typedef struct optEntSLegCrsReqRequestTag
{
  dataHeaderT header;
  optBscEntSLegCrsReqRequestT basic;
} optEntSLegCrsReqRequestT, *pOptEntSLegCrsReqRequestT;


#endif  /* _OPT_ENT_S_LEG_CRS_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _OPT_ENT_S_LEG_CRS_REQ_RESPONSE_T_
#define _OPT_ENT_S_LEG_CRS_REQ_RESPONSE_T_

typedef struct optEntSLegCrsReqResponseTag
{
  dataHeaderT header;
} optEntSLegCrsReqResponseT, *pOptEntSLegCrsReqResponseT;


#endif  /* _OPT_ENT_S_LEG_CRS_REQ_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _ENTSLEGCRSREQ_HXX_ */

/******************************************************************************/
/* End of file EntSLegCrsReq.hxx */
/******************************************************************************/
