/* Generated by Xgen from: E110.03.02 SIR 102640 on: 2008-02-29 14:35 */
/*******************************************************************************
* 2008 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   InqCsdDetl.hxx
*
*  DESCRIPTION: Layouts used for
*               Inquire CSD Detail
*
*******************************************************************************/

#ifndef _INQCSDDETL_HXX_
#define _INQCSDDETL_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/******************************************************************************/

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>

/******************************************************************************/

#define EXT_INQ_CSD_DETL_REC_MAX                 5

/******************************************************************************/

#ifndef _EXT_INQ_CSD_DETL_REQUEST_T_
#define _EXT_INQ_CSD_DETL_REQUEST_T_

typedef struct extInqCsdDetlRequestTag
{
    char             csdId           [DRIV_CSD_ID_LEN];
} extInqCsdDetlRequestT, *pExtInqCsdDetlRequestT;

#endif  /* _EXT_INQ_CSD_DETL_REQUEST_T_ */

/******************************************************************************/

#ifndef _INQ_CSD_DETL_REQUEST_T_
#define _INQ_CSD_DETL_REQUEST_T_

typedef struct inqCsdDetlRequestTag
{
    dataHeaderT      header;
    extInqCsdDetlRequestT extension;
} inqCsdDetlRequestT, *pInqCsdDetlRequestT;

#endif  /* _INQ_CSD_DETL_REQUEST_T_ */

/******************************************************************************/

#ifndef _BSC_INQ_CSD_DETL_RESPONSE_T_
#define _BSC_INQ_CSD_DETL_RESPONSE_T_

typedef struct bscInqCsdDetlResponseTag
{
    char             dateLstUpdDat   [DRIV_TIMESTAMP_LEN];
} bscInqCsdDetlResponseT, *pBscInqCsdDetlResponseT;

#endif  /* _BSC_INQ_CSD_DETL_RESPONSE_T_ */

/******************************************************************************/

#ifndef _EXT_INQ_CSD_DETL_RESPONSE_T_
#define _EXT_INQ_CSD_DETL_RESPONSE_T_

typedef struct extInqCsdDetlResponseTag
{
    char             csdLngNam       [DRIV_CSD_LNG_NAM_LEN];
    pstAddGrpT       pstAddGrp;
    char             csdSwiftAdd     [DRIV_CSD_SWIFT_ADD_LEN];
    char             csdCldrCod      [CSD_CLDR_COD_LEN];
    char             csdCldrCodNew   [CSD_CLDR_COD_NEW_LEN];
    char             csdDeadlTim     [DRIV_TIME_LEN];
    char             csdDeadlTimNew  [DRIV_TIME_LEN];
    ctctTextGrpT     ctctTextGrp     [EXT_INQ_CSD_DETL_REC_MAX];
} extInqCsdDetlResponseT, *pExtInqCsdDetlResponseT;

#endif  /* _EXT_INQ_CSD_DETL_RESPONSE_T_ */

/******************************************************************************/

#ifndef _INQ_CSD_DETL_RESPONSE_T_
#define _INQ_CSD_DETL_RESPONSE_T_

typedef struct inqCsdDetlResponseTag
{
    dataHeaderT      header;
    bscInqCsdDetlResponseT basic;
    extInqCsdDetlResponseT extension;
} inqCsdDetlResponseT, *pInqCsdDetlResponseT;

#endif  /* _INQ_CSD_DETL_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _INQCSDDETL_HXX_ */

/******************************************************************************/
/* End of file InqCsdDetl.hxx */
/******************************************************************************/
