/* Generated by Xgen from: E110.03.08 SIR 103290 on: 2008-04-02 14:05 */
/*******************************************************************************
* 2008 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   InqDlyMgn.hxx
*
*  DESCRIPTION: Layouts used for
*               Inquire Daily Margin
*
*******************************************************************************/

#ifndef _INQDLYMGN_HXX_
#define _INQDLYMGN_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/******************************************************************************/

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>

/******************************************************************************/

#define EXT_INQ_DLY_MGN_REC_MAX                  45

/******************************************************************************/

#ifndef _BSC_INQ_DLY_MGN_REQUEST_T_
#define _BSC_INQ_DLY_MGN_REQUEST_T_

typedef struct bscInqDlyMgnRequestTag
{
    char             membClgIdCod    [MEMB_CLG_ID_COD_LEN];
    char             membExchIdCod   [MEMB_EXCH_ID_COD_LEN];
    char             currTypCod      [CURR_TYP_COD_LEN];
    char             keyDataCtrlBlk  [KEY_DATA_CTRL_BLK_LEN];
} bscInqDlyMgnRequestT, *pBscInqDlyMgnRequestT;

#endif  /* _BSC_INQ_DLY_MGN_REQUEST_T_ */

/******************************************************************************/

#ifndef _INQ_DLY_MGN_REQUEST_T_
#define _INQ_DLY_MGN_REQUEST_T_

typedef struct inqDlyMgnRequestTag
{
    dataHeaderT      header;
    bscInqDlyMgnRequestT basic;
} inqDlyMgnRequestT, *pInqDlyMgnRequestT;

#endif  /* _INQ_DLY_MGN_REQUEST_T_ */

/******************************************************************************/

#ifndef _BSC_INQ_DLY_MGN_RESPONSE_T_
#define _BSC_INQ_DLY_MGN_RESPONSE_T_

typedef struct bscInqDlyMgnResponseTag
{
    char             keyDataCtrlBlk  [KEY_DATA_CTRL_BLK_LEN];
    char             mliRecCtr       [DRIV_MLI_REC_CTR_LEN];
} bscInqDlyMgnResponseT, *pBscInqDlyMgnResponseT;

#endif  /* _BSC_INQ_DLY_MGN_RESPONSE_T_ */

/******************************************************************************/

#ifndef _EXT_INQ_DLY_MGN_REC_T_
#define _EXT_INQ_DLY_MGN_REC_T_

typedef struct extInqDlyMgnRecTag
{
    acctTypCodGrpT   acctTypCodGrp;
    char             optPrmMgn       [DRIV_AMOUNT_LEN];
    char             futSprdMgn      [DRIV_AMOUNT_LEN];
    char             addlMgn         [DRIV_AMOUNT_LEN];
    char             dlvMgn          [DRIV_AMOUNT_LEN];
    char             mgnReqrAmnt     [DRIV_AMOUNT_LEN];
} extInqDlyMgnRecT, *pExtInqDlyMgnRecT;

#endif  /* _EXT_INQ_DLY_MGN_REC_T_ */

/******************************************************************************/

#ifndef _EXT_INQ_DLY_MGN_RESPONSE_T_
#define _EXT_INQ_DLY_MGN_RESPONSE_T_

typedef struct extInqDlyMgnResponseTag
{
    char             clgMembMgnReqr  [DRIV_AMOUNT_LEN];
    char             valUnknownInd;
    extInqDlyMgnRecT extInqDlyMgnRec [EXT_INQ_DLY_MGN_REC_MAX];
} extInqDlyMgnResponseT, *pExtInqDlyMgnResponseT;

#endif  /* _EXT_INQ_DLY_MGN_RESPONSE_T_ */

/******************************************************************************/

#ifndef _INQ_DLY_MGN_RESPONSE_T_
#define _INQ_DLY_MGN_RESPONSE_T_

typedef struct inqDlyMgnResponseTag
{
    dataHeaderT      header;
    bscInqDlyMgnResponseT basic;
    extInqDlyMgnResponseT extension;
} inqDlyMgnResponseT, *pInqDlyMgnResponseT;

#endif  /* _INQ_DLY_MGN_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _INQDLYMGN_HXX_ */

/******************************************************************************/
/* End of file InqDlyMgn.hxx */
/******************************************************************************/
