/* Generated by Xgen from: E120.14.02 SIR 127559 on: 2009-04-03 10:55 */
/*******************************************************************************
* 2009 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   InqStratOtcBlkTrd.hxx
*
*  DESCRIPTION: Layouts used for
*               Inquire Strategy OTC Block Trade
*
*******************************************************************************/

#ifndef _INQSTRATOTCBLKTRD_HXX_
#define _INQSTRATOTCBLKTRD_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/******************************************************************************/

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>

/******************************************************************************/

#define BSC_INQ_STRAT_OTC_BLK_TRD_REC_MAX        2
#define EXT_INQ_STRAT_OTC_BLK_TRD_REC_MAX        2

/******************************************************************************/

#ifndef _BSC_INQ_STRAT_OTC_BLK_TRD_REQUEST_T_
#define _BSC_INQ_STRAT_OTC_BLK_TRD_REQUEST_T_

typedef struct bscInqStratOtcBlkTrdRequestTag
{
    char             trnIdNo         [TRN_ID_NO_LEN];
    trdrIdGrpT       trdrIdGrp;
} bscInqStratOtcBlkTrdRequestT, *pBscInqStratOtcBlkTrdRequestT;

#endif  /* _BSC_INQ_STRAT_OTC_BLK_TRD_REQUEST_T_ */

/******************************************************************************/

#ifndef _INQ_STRAT_OTC_BLK_TRD_REQUEST_T_
#define _INQ_STRAT_OTC_BLK_TRD_REQUEST_T_

typedef struct inqStratOtcBlkTrdRequestTag
{
    dataHeaderT      header;
    bscInqStratOtcBlkTrdRequestT basic;
} inqStratOtcBlkTrdRequestT, *pInqStratOtcBlkTrdRequestT;

#endif  /* _INQ_STRAT_OTC_BLK_TRD_REQUEST_T_ */

/******************************************************************************/

#ifndef _BSC_INQ_STRAT_OTC_BLK_TRD_REC_T_
#define _BSC_INQ_STRAT_OTC_BLK_TRD_REC_T_

typedef struct bscInqStratOtcBlkTrdRecTag
{
    char             opnClsCod;
    char             membCtpyIdCod   [MEMB_CTPY_ID_COD_LEN];
    trdrIdGrpT       trdrIdGrp;
    char             blkTrdStsCod;
} bscInqStratOtcBlkTrdRecT, *pBscInqStratOtcBlkTrdRecT;

#endif  /* _BSC_INQ_STRAT_OTC_BLK_TRD_REC_T_ */

/******************************************************************************/

#ifndef _BSC_INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_
#define _BSC_INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_

typedef struct bscInqStratOtcBlkTrdResponseTag
{
    char             buyCod;
    stratIdGrpT      stratIdGrp;
    stratEquLegGrpT  stratEquLegGrp;
    stratTrdNoGrpT   stratTrdNoGrp;
    char             trdXQty         [DRIV_VOLUME_LEN];
    char             trdMtchPrc      [DRIV_PRICE_LEN];
    char             currTypCod      [CURR_TYP_COD_LEN];
    char             dateLstUpdDat   [DRIV_TIMESTAMP_LEN];
    bscInqStratOtcBlkTrdRecT bscInqStratOtcBlkTrdRec [BSC_INQ_STRAT_OTC_BLK_TRD_REC_MAX];
} bscInqStratOtcBlkTrdResponseT, *pBscInqStratOtcBlkTrdResponseT;

#endif  /* _BSC_INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_ */

/******************************************************************************/

#ifndef _EXT_INQ_STRAT_OTC_BLK_TRD_REC_T_
#define _EXT_INQ_STRAT_OTC_BLK_TRD_REC_T_

typedef struct extInqStratOtcBlkTrdRecTag
{
    acctTypCodGrpT   acctTypCodGrp;
    txtGrpT          txtGrp;
    char             membClgIdCod    [MEMB_CLG_ID_COD_LEN];
} extInqStratOtcBlkTrdRecT, *pExtInqStratOtcBlkTrdRecT;

#endif  /* _EXT_INQ_STRAT_OTC_BLK_TRD_REC_T_ */

/******************************************************************************/

#ifndef _EXT_INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_
#define _EXT_INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_

typedef struct extInqStratOtcBlkTrdResponseTag
{
    extInqStratOtcBlkTrdRecT extInqStratOtcBlkTrdRec [EXT_INQ_STRAT_OTC_BLK_TRD_REC_MAX];
} extInqStratOtcBlkTrdResponseT, *pExtInqStratOtcBlkTrdResponseT;

#endif  /* _EXT_INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_ */

/******************************************************************************/

#ifndef _INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_
#define _INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_

typedef struct inqStratOtcBlkTrdResponseTag
{
    dataHeaderT      header;
    bscInqStratOtcBlkTrdResponseT basic;
    extInqStratOtcBlkTrdResponseT extension;
} inqStratOtcBlkTrdResponseT, *pInqStratOtcBlkTrdResponseT;

#endif  /* _INQ_STRAT_OTC_BLK_TRD_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _INQSTRATOTCBLKTRD_HXX_ */

/******************************************************************************/
/* End of file InqStratOtcBlkTrd.hxx */
/******************************************************************************/
