/* Generated by Xgen from: E100.00.01 SIR 68471 on: 2006-11-23 09:55 */
/*******************************************************************************
* 2006 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   InqVolTrd.hxx
*
*  DESCRIPTION: Layouts used for
*               Inquire Vola Trade
*
*******************************************************************************/

#ifndef _INQVOLTRD_HXX_
#define _INQVOLTRD_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/******************************************************************************/

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>

/******************************************************************************/

#define FUT_BSC_INQ_VOL_TRD_REC_MAX              2
#define FUT_EXT_INQ_VOL_TRD_REC_MAX              2

/******************************************************************************/

#ifndef _FUT_BSC_INQ_VOL_TRD_REQUEST_T_
#define _FUT_BSC_INQ_VOL_TRD_REQUEST_T_

typedef struct futBscInqVolTrdRequestTag
{
    char             trnIdNo         [TRN_ID_NO_LEN];
    trdrIdGrpT       trdrIdGrp;
} futBscInqVolTrdRequestT, *pFutBscInqVolTrdRequestT;

#endif  /* _FUT_BSC_INQ_VOL_TRD_REQUEST_T_ */

/******************************************************************************/

#ifndef _FUT_INQ_VOL_TRD_REQUEST_T_
#define _FUT_INQ_VOL_TRD_REQUEST_T_

typedef struct futInqVolTrdRequestTag
{
    dataHeaderT      header;
    futBscInqVolTrdRequestT basic;
} futInqVolTrdRequestT, *pFutInqVolTrdRequestT;

#endif  /* _FUT_INQ_VOL_TRD_REQUEST_T_ */

/******************************************************************************/

#ifndef _FUT_BSC_INQ_VOL_TRD_REC_T_
#define _FUT_BSC_INQ_VOL_TRD_REC_T_

typedef struct futBscInqVolTrdRecTag
{
    char             opnClsCod;
    char             membCtpyIdCod   [MEMB_CTPY_ID_COD_LEN];
    trdrIdGrpT       trdrIdGrp;
} futBscInqVolTrdRecT, *pFutBscInqVolTrdRecT;

#endif  /* _FUT_BSC_INQ_VOL_TRD_REC_T_ */

/******************************************************************************/

#ifndef _OPT_CNTR_ID_VOLA_GRP_T_
#define _OPT_CNTR_ID_VOLA_GRP_T_

typedef struct optCntrIdVolaGrpTag
{
    char             prodId2         [DRIV_PROD_ID2_LEN];
    char             cntrClasCod2;
    char             cntrExpMthDat2  [CNTR_EXP_MTH_DAT2_LEN];
    char             cntrExpYrDat2   [CNTR_EXP_YR_DAT2_LEN];
    char             cntrExerPrc2    [CNTR_EXER_PRC2_LEN];
    char             cntrVersNo2;
} optCntrIdVolaGrpT, *pOptCntrIdVolaGrpT;

#endif  /* _OPT_CNTR_ID_VOLA_GRP_T_ */

/******************************************************************************/

#ifndef _FUT_BSC_INQ_VOL_TRD_RESPONSE_T_
#define _FUT_BSC_INQ_VOL_TRD_RESPONSE_T_

typedef struct futBscInqVolTrdResponseTag
{
    char             buyCod;
    futCntrIdGrpT    futCntrIdGrp;
    char             trdNo           [TRD_NO_LEN];
    char             trdXQty         [DRIV_VOLUME_LEN];
    char             trdMtchPrc      [DRIV_PRICE_LEN];
    char             dateLstUpdDat   [DRIV_TIMESTAMP_LEN];
    futBscInqVolTrdRecT futBscInqVolTrdRec [FUT_BSC_INQ_VOL_TRD_REC_MAX];
    optCntrIdVolaGrpT optCntrIdVolaGrp;
} futBscInqVolTrdResponseT, *pFutBscInqVolTrdResponseT;

#endif  /* _FUT_BSC_INQ_VOL_TRD_RESPONSE_T_ */

/******************************************************************************/

#ifndef _FUT_EXT_INQ_VOL_TRD_REC_T_
#define _FUT_EXT_INQ_VOL_TRD_REC_T_

typedef struct futExtInqVolTrdRecTag
{
    acctTypCodGrpT   acctTypCodGrp;
    txtGrpT          txtGrp;
    char             membClgIdCod    [MEMB_CLG_ID_COD_LEN];
} futExtInqVolTrdRecT, *pFutExtInqVolTrdRecT;

#endif  /* _FUT_EXT_INQ_VOL_TRD_REC_T_ */

/******************************************************************************/

#ifndef _FUT_EXT_INQ_VOL_TRD_RESPONSE_T_
#define _FUT_EXT_INQ_VOL_TRD_RESPONSE_T_

typedef struct futExtInqVolTrdResponseTag
{
    futExtInqVolTrdRecT futExtInqVolTrdRec [FUT_EXT_INQ_VOL_TRD_REC_MAX];
    char             trnIdNoOpt      [TRN_ID_NO_LEN];
    char             trdQtyOpt       [DRIV_VOLUME_LEN];
    char             trdMtchPrcOpt   [DRIV_PRICE_LEN];
    char             usedQtyOpt      [DRIV_VOLUME_LEN];
} futExtInqVolTrdResponseT, *pFutExtInqVolTrdResponseT;

#endif  /* _FUT_EXT_INQ_VOL_TRD_RESPONSE_T_ */

/******************************************************************************/

#ifndef _FUT_INQ_VOL_TRD_RESPONSE_T_
#define _FUT_INQ_VOL_TRD_RESPONSE_T_

typedef struct futInqVolTrdResponseTag
{
    dataHeaderT      header;
    futBscInqVolTrdResponseT basic;
    futExtInqVolTrdResponseT extension;
} futInqVolTrdResponseT, *pFutInqVolTrdResponseT;

#endif  /* _FUT_INQ_VOL_TRD_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _INQVOLTRD_HXX_ */

/******************************************************************************/
/* End of file InqVolTrd.hxx */
/******************************************************************************/
