/* Generated by Xgen from: E100.04.19 SIR 79062 on: 2007-05-15 09:20 */
/*******************************************************************************
* 2007 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   ModMembProdQty.hxx
*
*  DESCRIPTION: Layouts used for
*               Modify Member Product Quantities
*
*******************************************************************************/

#ifndef _MODMEMBPRODQTY_HXX_
#define _MODMEMBPRODQTY_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/******************************************************************************/

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>

/******************************************************************************/

#define BSC_MOD_MEMB_PROD_QTY_GRP_MAX            80
#define BSC_MTN_MEMB_PROD_QTY_REC_MAX            100

/******************************************************************************/

#ifndef _BSC_MOD_MEMB_PROD_QTY_GRP_T_
#define _BSC_MOD_MEMB_PROD_QTY_GRP_T_

typedef struct bscModMembProdQtyGrpTag
{
    prodGrpIdGrpT    prodGrpIdGrp;
    char             prodId          [PROD_ID_LEN];
    char             maxOrdrQty      [DRIV_VOLUME_LEN];
    char             maxCalSprdQty   [DRIV_VOLUME_LEN];
    char             maxWhsQty       [DRIV_VOLUME_LEN];
} bscModMembProdQtyGrpT, *pBscModMembProdQtyGrpT;

#endif  /* _BSC_MOD_MEMB_PROD_QTY_GRP_T_ */

/******************************************************************************/

#ifndef _BSC_MOD_MEMB_PROD_QTY_REQUEST_T_
#define _BSC_MOD_MEMB_PROD_QTY_REQUEST_T_

typedef struct bscModMembProdQtyRequestTag
{
    char             membExchIdCod   [MEMB_EXCH_ID_COD_LEN];
    char             mliRecCtr       [DRIV_MLI_REC_CTR_LEN];
    bscModMembProdQtyGrpT bscModMembProdQtyGrp [BSC_MOD_MEMB_PROD_QTY_GRP_MAX];
} bscModMembProdQtyRequestT, *pBscModMembProdQtyRequestT;

#endif  /* _BSC_MOD_MEMB_PROD_QTY_REQUEST_T_ */

/******************************************************************************/

#ifndef _MOD_MEMB_PROD_QTY_REQUEST_T_
#define _MOD_MEMB_PROD_QTY_REQUEST_T_

typedef struct modMembProdQtyRequestTag
{
    dataHeaderT      header;
    bscModMembProdQtyRequestT basic;
} modMembProdQtyRequestT, *pModMembProdQtyRequestT;

#endif  /* _MOD_MEMB_PROD_QTY_REQUEST_T_ */

/******************************************************************************/

#ifndef _BSC_MOD_MEMB_PROD_QTY_REC_T_
#define _BSC_MOD_MEMB_PROD_QTY_REC_T_

typedef struct bscModMembProdQtyRecTag
{
    char             rtnCod          [RTN_COD_LEN];
} bscModMembProdQtyRecT, *pBscModMembProdQtyRecT;

#endif  /* _BSC_MOD_MEMB_PROD_QTY_REC_T_ */

/******************************************************************************/

#ifndef _BSC_MOD_MEMB_PROD_QTY_RESPONSE_T_
#define _BSC_MOD_MEMB_PROD_QTY_RESPONSE_T_

typedef struct bscModMembProdQtyResponseTag
{
    char             mliRecCtr       [DRIV_MLI_REC_CTR_LEN];
    bscModMembProdQtyRecT bscModMembProdQtyRec [BSC_MTN_MEMB_PROD_QTY_REC_MAX];
} bscModMembProdQtyResponseT, *pBscModMembProdQtyResponseT;

#endif  /* _BSC_MOD_MEMB_PROD_QTY_RESPONSE_T_ */

/******************************************************************************/

#ifndef _MOD_MEMB_PROD_QTY_RESPONSE_T_
#define _MOD_MEMB_PROD_QTY_RESPONSE_T_

typedef struct modMembProdQtyResponseTag
{
    dataHeaderT      header;
    bscModMembProdQtyResponseT basic;
} modMembProdQtyResponseT, *pModMembProdQtyResponseT;

#endif  /* _MOD_MEMB_PROD_QTY_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _MODMEMBPRODQTY_HXX_ */

/******************************************************************************/
/* End of file ModMembProdQty.hxx */
/******************************************************************************/
