/* Generated by Xgen from: E120.07.02 SIR 123667 on: 2009-02-16 10:26 */
/*******************************************************************************
* 2009 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   InqEfsTrd.hxx
*
*  DESCRIPTION: Layouts used for
*               Inquire EFS Trade
*
*******************************************************************************/

#ifndef _INQEFSTRD_HXX_
#define _INQEFSTRD_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/******************************************************************************/

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>

/******************************************************************************/

#define FUT_BSC_INQ_EFS_TRD_REC_MAX              2

/******************************************************************************/

#ifndef _FUT_BSC_INQ_EFS_TRD_REQUEST_T_
#define _FUT_BSC_INQ_EFS_TRD_REQUEST_T_

typedef struct futBscInqEfsTrdRequestTag
{
    char             trnIdNo         [TRN_ID_NO_LEN];
    trdrIdGrpT       trdrIdGrp;
} futBscInqEfsTrdRequestT, *pFutBscInqEfsTrdRequestT;

#endif  /* _FUT_BSC_INQ_EFS_TRD_REQUEST_T_ */

/******************************************************************************/

#ifndef _FUT_INQ_EFS_TRD_REQUEST_T_
#define _FUT_INQ_EFS_TRD_REQUEST_T_

typedef struct futInqEfsTrdRequestTag
{
    dataHeaderT      header;
    futBscInqEfsTrdRequestT basic;
} futInqEfsTrdRequestT, *pFutInqEfsTrdRequestT;

#endif  /* _FUT_INQ_EFS_TRD_REQUEST_T_ */

/******************************************************************************/

#ifndef _FUT_BSC_INQ_EFS_TRD_REC_T_
#define _FUT_BSC_INQ_EFS_TRD_REC_T_

typedef struct futBscInqEfsTrdRecTag
{
    char             opnClsCod;
    char             membCtpyIdCod   [MEMB_CTPY_ID_COD_LEN];
    trdrIdGrpT       trdrIdGrp;
    acctTypCodGrpT   acctTypCodGrp;
    txtGrpT          txtGrp;
    char             membExchIdCodTo [DRIV_MEMB_EXCH_ID_COD_TO_LEN];
    char             whsTrdStsCod;
} futBscInqEfsTrdRecT, *pFutBscInqEfsTrdRecT;

#endif  /* _FUT_BSC_INQ_EFS_TRD_REC_T_ */

/******************************************************************************/

#ifndef _FUT_BSC_INQ_EFS_TRD_RESPONSE_T_
#define _FUT_BSC_INQ_EFS_TRD_RESPONSE_T_

typedef struct futBscInqEfsTrdResponseTag
{
    char             buyCod;
    futCntrIdGrpT    futCntrIdGrp;
    char             trdNo           [TRD_NO_LEN];
    char             nomVal          [NOM_VAL_LEN];
    char             trdXQty         [DRIV_VOLUME_LEN];
    char             futPrc          [DRIV_PRICE_LEN];
    char             setlDat         [DRIV_DATE_LEN];
    cshLegEfsGrpT    cshLegEfsGrp;
    char             exchRat         [EXCH_RAT_LEN];
    char             undrCurrCod     [UNDR_CURR_COD_LEN];
    char             swapCust1       [SWAP_CUST1_LEN];
    char             swapCust2       [SWAP_CUST2_LEN];
    futBscInqEfsTrdRecT futBscInqEfsTrdRec [FUT_BSC_INQ_EFS_TRD_REC_MAX];
    char             dateLstUpdDat   [DRIV_TIMESTAMP_LEN];
} futBscInqEfsTrdResponseT, *pFutBscInqEfsTrdResponseT;

#endif  /* _FUT_BSC_INQ_EFS_TRD_RESPONSE_T_ */

/******************************************************************************/

#ifndef _FUT_INQ_EFS_TRD_RESPONSE_T_
#define _FUT_INQ_EFS_TRD_RESPONSE_T_

typedef struct futInqEfsTrdResponseTag
{
    dataHeaderT      header;
    futBscInqEfsTrdResponseT basic;
} futInqEfsTrdResponseT, *pFutInqEfsTrdResponseT;

#endif  /* _FUT_INQ_EFS_TRD_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _INQEFSTRD_HXX_ */

/******************************************************************************/
/* End of file InqEfsTrd.hxx */
/******************************************************************************/
