/* Generated by Xgen from: E110.03.08 SIR 103290 on: 2008-04-02 14:05 */
/*******************************************************************************
* 2008 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   InqSpcEquColl.hxx
*
*  DESCRIPTION: Layouts used for
*               Inquire Specific Equity Collateral
*
*******************************************************************************/

#ifndef _INQSPCEQUCOLL_HXX_
#define _INQSPCEQUCOLL_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/******************************************************************************/

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>

/******************************************************************************/

#define BSC_INQ_SPC_EQU_COLL_REC_MAX             25

/******************************************************************************/

#ifndef _BSC_INQ_SPC_EQU_COLL_REQUEST_T_
#define _BSC_INQ_SPC_EQU_COLL_REQUEST_T_

typedef struct bscInqSpcEquCollRequestTag
{
    char             membExchIdCod   [MEMB_EXCH_ID_COD_LEN];
    acctTypCodGrpT   acctTypCodGrp;
    char             isinCod         [ISIN_COD_LEN];
    char             csdId           [DRIV_CSD_ID_LEN];
    char             csdPldgAcctNo   [CSD_ACCT_NO_LEN];
    char             keyDataCtrlBlk  [KEY_DATA_CTRL_BLK_LEN];
} bscInqSpcEquCollRequestT, *pBscInqSpcEquCollRequestT;

#endif  /* _BSC_INQ_SPC_EQU_COLL_REQUEST_T_ */

/******************************************************************************/

#ifndef _INQ_SPC_EQU_COLL_REQUEST_T_
#define _INQ_SPC_EQU_COLL_REQUEST_T_

typedef struct inqSpcEquCollRequestTag
{
    dataHeaderT      header;
    bscInqSpcEquCollRequestT basic;
} inqSpcEquCollRequestT, *pInqSpcEquCollRequestT;

#endif  /* _INQ_SPC_EQU_COLL_REQUEST_T_ */

/******************************************************************************/

#ifndef _BSC_INQ_SPC_EQU_COLL_REC_T_
#define _BSC_INQ_SPC_EQU_COLL_REC_T_

typedef struct bscInqSpcEquCollRecTag
{
    char             membExchIdCod   [MEMB_EXCH_ID_COD_LEN];
    acctTypCodGrpT   acctTypCodGrp;
    char             isinCod         [ISIN_COD_LEN];
    char             currTypCod      [CURR_TYP_COD_LEN];
    char             spcEquCollQty   [DRIV_QUANTITY_LEN];
    char             avlBulkCollQty  [DRIV_QUANTITY_LEN];
    char             usedSecQty      [DRIV_QUANTITY_LEN];
    char             secEvalPrc      [DRIV_PRICE_LEN];
    char             evalPrcDispDcml [EVAL_PRC_DISP_DCML_LEN];
    char             dateLstUpdDat   [DRIV_TIMESTAMP_LEN];
    char             csdId           [DRIV_CSD_ID_LEN];
    char             csdPldgAcctNo   [CSD_ACCT_NO_LEN];
} bscInqSpcEquCollRecT, *pBscInqSpcEquCollRecT;

#endif  /* _BSC_INQ_SPC_EQU_COLL_REC_T_ */

/******************************************************************************/

#ifndef _BSC_INQ_SPC_EQU_COLL_RESPONSE_T_
#define _BSC_INQ_SPC_EQU_COLL_RESPONSE_T_

typedef struct bscInqSpcEquCollResponseTag
{
    char             keyDataCtrlBlk  [KEY_DATA_CTRL_BLK_LEN];
    char             mliRecCtr       [DRIV_MLI_REC_CTR_LEN];
    bscInqSpcEquCollRecT bscInqSpcEquCollRec [BSC_INQ_SPC_EQU_COLL_REC_MAX];
} bscInqSpcEquCollResponseT, *pBscInqSpcEquCollResponseT;

#endif  /* _BSC_INQ_SPC_EQU_COLL_RESPONSE_T_ */

/******************************************************************************/

#ifndef _INQ_SPC_EQU_COLL_RESPONSE_T_
#define _INQ_SPC_EQU_COLL_RESPONSE_T_

typedef struct inqSpcEquCollResponseTag
{
    dataHeaderT      header;
    bscInqSpcEquCollResponseT basic;
} inqSpcEquCollResponseT, *pInqSpcEquCollResponseT;

#endif  /* _INQ_SPC_EQU_COLL_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _INQSPCEQUCOLL_HXX_ */

/******************************************************************************/
/* End of file InqSpcEquColl.hxx */
/******************************************************************************/
