/* Generated by Xgen from: E90.05.00 SIR 48700 on: 2006-05-05 08:18 */
/*******************************************************************************
* 2006 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   ModStratBlkAuctReq.hxx
*
*  DESCRIPTION: Layouts used for
*               Modify Strategy Block Auction Request
*
*******************************************************************************/

#ifndef _MODSTRATBLKAUCTREQ_HXX_
#define _MODSTRATBLKAUCTREQ_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/******************************************************************************/

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>

/******************************************************************************/


/******************************************************************************/

#ifndef _BSC_MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_
#define _BSC_MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_

typedef struct bscModStratBlkAuctReqRequestTag
{
    char             buyCod;
    char             ordrNo          [DRIV_ORDR_NO_LEN];
    stratIdGrpT      stratIdGrp;
    trdrIdGrpT       trdrIdGrp;
    char             ordrExePrc      [DRIV_PRICE_LEN];
    char             opnClsCod;
    char             dateLstUpdDat   [DRIV_TIMESTAMP_LEN];
} bscModStratBlkAuctReqRequestT, *pBscModStratBlkAuctReqRequestT;

#endif  /* _BSC_MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _EXT_MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_
#define _EXT_MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_

typedef struct extModStratBlkAuctReqRequestTag
{
    acctTypCodGrpT   acctTypCodGrp;
    txtGrpT          txtGrp;
    char             membExchIdCodTo [DRIV_MEMB_EXCH_ID_COD_TO_LEN];
} extModStratBlkAuctReqRequestT, *pExtModStratBlkAuctReqRequestT;

#endif  /* _EXT_MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_
#define _MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_

typedef struct modStratBlkAuctReqRequestTag
{
    dataHeaderT      header;
    bscModStratBlkAuctReqRequestT basic;
    extModStratBlkAuctReqRequestT extension;
} modStratBlkAuctReqRequestT, *pModStratBlkAuctReqRequestT;

#endif  /* _MOD_STRAT_BLK_AUCT_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _BSC_MOD_STRAT_BLK_AUCT_REQ_RESPONSE_T_
#define _BSC_MOD_STRAT_BLK_AUCT_REQ_RESPONSE_T_

typedef struct bscModStratBlkAuctReqResponseTag
{
    char             ordrNo          [DRIV_ORDR_NO_LEN];
    char             dateLstUpdDat   [DRIV_TIMESTAMP_LEN];
} bscModStratBlkAuctReqResponseT, *pBscModStratBlkAuctReqResponseT;

#endif  /* _BSC_MOD_STRAT_BLK_AUCT_REQ_RESPONSE_T_ */

/******************************************************************************/

#ifndef _MOD_STRAT_BLK_AUCT_REQ_RESPONSE_T_
#define _MOD_STRAT_BLK_AUCT_REQ_RESPONSE_T_

typedef struct modStratBlkAuctReqResponseTag
{
    dataHeaderT      header;
    bscModStratBlkAuctReqResponseT basic;
} modStratBlkAuctReqResponseT, *pModStratBlkAuctReqResponseT;

#endif  /* _MOD_STRAT_BLK_AUCT_REQ_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _MODSTRATBLKAUCTREQ_HXX_ */

/******************************************************************************/
/* End of file ModStratBlkAuctReq.hxx */
/******************************************************************************/
