/* Generated by Xgen from: E61.02.00 on: 2003-03-12 16:09 */
/*******************************************************************************
* 2003 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   RejTakUpTrn.hxx
*
*  DESCRIPTION: see documentation
*
*******************************************************************************/

#ifndef _REJTAKUPTRN_HXX_
#define _REJTAKUPTRN_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>


/******************************************************************************/

#ifndef _FUT_BSC_REJ_TAK_UP_TRN_REQUEST_T_
#define _FUT_BSC_REJ_TAK_UP_TRN_REQUEST_T_

typedef struct futBscRejTakUpTrnRequestTag
{
  char membClgIdCodTo[DRIV_MEMB_CLG_ID_COD_TO_LEN];
  char membExchIdCodTo[DRIV_MEMB_EXCH_ID_COD_TO_LEN];
  futCntrIdGrpT futCntrIdGrp;
  char trnDat[DRIV_DATE_LEN];
  char ordrNo[DRIV_ORDR_NO_LEN];
  char trnIdNo[TRN_ID_NO_LEN];
  trnIdSfxKeyGrpT trnIdSfxKeyGrp;
  char buyCod;
  char dateLstUpdDat[DRIV_TIMESTAMP_LEN];
} futBscRejTakUpTrnRequestT, *pFutBscRejTakUpTrnRequestT;


#endif  /* _FUT_BSC_REJ_TAK_UP_TRN_REQUEST_T_ */

/******************************************************************************/

#ifndef _FUT_REJ_TAK_UP_TRN_REQUEST_T_
#define _FUT_REJ_TAK_UP_TRN_REQUEST_T_

typedef struct futRejTakUpTrnRequestTag
{
  dataHeaderT header;
  futBscRejTakUpTrnRequestT basic;
} futRejTakUpTrnRequestT, *pFutRejTakUpTrnRequestT;


#endif  /* _FUT_REJ_TAK_UP_TRN_REQUEST_T_ */

/******************************************************************************/

#ifndef _FUT_BSC_REJ_TAK_UP_TRN_RESPONSE_T_
#define _FUT_BSC_REJ_TAK_UP_TRN_RESPONSE_T_

typedef struct futBscRejTakUpTrnResponseTag
{
  char gutSts;
  char dateLstUpdDat[DRIV_TIMESTAMP_LEN];
} futBscRejTakUpTrnResponseT, *pFutBscRejTakUpTrnResponseT;


#endif  /* _FUT_BSC_REJ_TAK_UP_TRN_RESPONSE_T_ */

/******************************************************************************/

#ifndef _FUT_REJ_TAK_UP_TRN_RESPONSE_T_
#define _FUT_REJ_TAK_UP_TRN_RESPONSE_T_

typedef struct futRejTakUpTrnResponseTag
{
  dataHeaderT header;
  futBscRejTakUpTrnResponseT basic;
} futRejTakUpTrnResponseT, *pFutRejTakUpTrnResponseT;


#endif  /* _FUT_REJ_TAK_UP_TRN_RESPONSE_T_ */

/******************************************************************************/

#ifndef _OPT_BSC_REJ_TAK_UP_TRN_REQUEST_T_
#define _OPT_BSC_REJ_TAK_UP_TRN_REQUEST_T_

typedef struct optBscRejTakUpTrnRequestTag
{
  char membClgIdCodTo[DRIV_MEMB_CLG_ID_COD_TO_LEN];
  char membExchIdCodTo[DRIV_MEMB_EXCH_ID_COD_TO_LEN];
  optCntrIdGrpT optCntrIdGrp;
  char trnDat[DRIV_DATE_LEN];
  char ordrNo[DRIV_ORDR_NO_LEN];
  char trnIdNo[TRN_ID_NO_LEN];
  trnIdSfxKeyGrpT trnIdSfxKeyGrp;
  char buyCod;
  char dateLstUpdDat[DRIV_TIMESTAMP_LEN];
} optBscRejTakUpTrnRequestT, *pOptBscRejTakUpTrnRequestT;


#endif  /* _OPT_BSC_REJ_TAK_UP_TRN_REQUEST_T_ */

/******************************************************************************/

#ifndef _OPT_REJ_TAK_UP_TRN_REQUEST_T_
#define _OPT_REJ_TAK_UP_TRN_REQUEST_T_

typedef struct optRejTakUpTrnRequestTag
{
  dataHeaderT header;
  optBscRejTakUpTrnRequestT basic;
} optRejTakUpTrnRequestT, *pOptRejTakUpTrnRequestT;


#endif  /* _OPT_REJ_TAK_UP_TRN_REQUEST_T_ */

/******************************************************************************/

#ifndef _OPT_BSC_REJ_TAK_UP_TRN_RESPONSE_T_
#define _OPT_BSC_REJ_TAK_UP_TRN_RESPONSE_T_

typedef struct optBscRejTakUpTrnResponseTag
{
  char gutSts;
  char dateLstUpdDat[DRIV_TIMESTAMP_LEN];
} optBscRejTakUpTrnResponseT, *pOptBscRejTakUpTrnResponseT;


#endif  /* _OPT_BSC_REJ_TAK_UP_TRN_RESPONSE_T_ */

/******************************************************************************/

#ifndef _OPT_REJ_TAK_UP_TRN_RESPONSE_T_
#define _OPT_REJ_TAK_UP_TRN_RESPONSE_T_

typedef struct optRejTakUpTrnResponseTag
{
  dataHeaderT header;
  optBscRejTakUpTrnResponseT basic;
} optRejTakUpTrnResponseT, *pOptRejTakUpTrnResponseT;


#endif  /* _OPT_REJ_TAK_UP_TRN_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _REJTAKUPTRN_HXX_ */

/******************************************************************************/
/* End of file RejTakUpTrn.hxx */
/******************************************************************************/
