///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace Finetuned
{
    /// <summary>
    /// The DB_FILE_Postgres recording.
    /// </summary>
    [TestModule("b5bd1716-b1ac-4748-98a8-705b38a60458", ModuleType.Recording, 1)]
    public partial class DB_FILE_Postgres : ITestModule
    {
        /// <summary>
        /// Holds an instance of the FinetunedRepository repository.
        /// </summary>
        public static FinetunedRepository repo = FinetunedRepository.Instance;

        static DB_FILE_Postgres instance = new DB_FILE_Postgres();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DB_FILE_Postgres()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DB_FILE_Postgres Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextProcess_Modeling_' at 65;7.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextProcess_Modeling_Info, new RecordItemIndex(0));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextProcess_Modeling_.Click("65;7");
            Delay.Milliseconds(1130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.MenuItemView_Process1' at 70;5.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.MenuItemView_Process1Info, new RecordItemIndex(1));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.MenuItemView_Process1.Click("70;5");
            Delay.Milliseconds(2870);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.ContainerVBox.ButtonNew' at 16;10.", repo.WebDocument10_200_41_76_8880.ContainerVBox.ButtonNewInfo, new RecordItemIndex(2));
            repo.WebDocument10_200_41_76_8880.ContainerVBox.ButtonNew.Click("16;10");
            Delay.Milliseconds(3580);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_1' at 15;7.", repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_1Info, new RecordItemIndex(3));
            repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_1.MoveTo("15;7");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2540);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 80;92.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvasInfo, new RecordItemIndex(4));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("80;92");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(3800);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_31' at 6;10.", repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_31Info, new RecordItemIndex(5));
            repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.PictureIcon_31.MoveTo("6;10");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2050);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 434;147.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvasInfo, new RecordItemIndex(6));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("434;147");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonParsers' at 68;5.", repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonParsersInfo, new RecordItemIndex(7));
            repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonParsers.Click("68;5");
            Delay.Milliseconds(4320);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerHBox.PictureIcon_5' at 9;18.", repo.WebDocumentLocalhost_8888.ContainerHBox.PictureIcon_5Info, new RecordItemIndex(8));
            repo.WebDocumentLocalhost_8888.ContainerHBox.PictureIcon_5.MoveTo("9;18");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2380);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 128;196.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvasInfo, new RecordItemIndex(9));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("128;196");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(3240);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonFormatters' at 26;12.", repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonFormattersInfo, new RecordItemIndex(10));
            repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonFormatters.Click("26;12");
            Delay.Milliseconds(2980);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'PictureIcon_91' at 14;4.", repo.PictureIcon_91Info, new RecordItemIndex(11));
            repo.PictureIcon_91.MoveTo("14;4");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2070);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas' at 279;90.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvasInfo, new RecordItemIndex(12));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas.MoveTo("279;90");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2320);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_3153' at 18;30.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_3153Info, new RecordItemIndex(13));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_3153.Click(MouseButtons.Right, "18;30");
            Delay.Milliseconds(1850);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 17;11.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(14));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("17;11");
            Delay.Milliseconds(1270);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId' at 20;8.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceIdInfo, new RecordItemIndex(15));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId.Click("20;8");
            Delay.Milliseconds(1990);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'src' with focus on 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId'.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceIdInfo, new RecordItemIndex(16));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId.PressKeys("src");
            Delay.Milliseconds(1080);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServerURL' at 7;12.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServerURLInfo, new RecordItemIndex(17));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServerURL.Click("7;12");
            Delay.Milliseconds(1550);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'jdbc:postgresql://10.200.20.36/devdb' with focus on 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServerURL'.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServerURLInfo, new RecordItemIndex(18));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServerURL.PressKeys("jdbc:postgresql://10.200.20.36/devdb");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextUserName' at 109;13.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextUserNameInfo, new RecordItemIndex(19));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextUserName.Click("109;13");
            Delay.Milliseconds(1070);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'postgres' with focus on 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextUserName'.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextUserNameInfo, new RecordItemIndex(20));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextUserName.PressKeys("postgres");
            Delay.Milliseconds(1470);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextPassword' at 92;9.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextPasswordInfo, new RecordItemIndex(21));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextPassword.Click("92;9");
            Delay.Milliseconds(1620);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'icefish{Tab}' with focus on 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextPassword'.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextPasswordInfo, new RecordItemIndex(22));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextPassword.PressKeys("icefish{Tab}");
            Delay.Milliseconds(1610);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'select MSGID,CNTRACTID,STATUS from Test_src where STATUS='OPEN''.", new RecordItemIndex(23));
            Keyboard.Press("select MSGID,CNTRACTID,STATUS from Test_src where STATUS='OPEN'");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextWaitInterval' at 55;12.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextWaitIntervalInfo, new RecordItemIndex(24));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextWaitInterval.Click("55;12");
            Delay.Milliseconds(480);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1 down}{NumPad0}{NumPad0}{NumPad0}{NumPad0}' with focus on 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextWaitInterval'.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextWaitIntervalInfo, new RecordItemIndex(25));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextWaitInterval.PressKeys("{NumPad1 down}{NumPad0}{NumPad0}{NumPad0}{NumPad0}");
            Delay.Milliseconds(4240);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInput1' at 28;7.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInput1Info, new RecordItemIndex(26));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInput1.Click("28;7");
            Delay.Milliseconds(1850);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ListList.TextPostGre_SQL' at 24;6.", repo.WebDocumentLocalhost_8888.ListList.TextPostGre_SQLInfo, new RecordItemIndex(27));
            repo.WebDocumentLocalhost_8888.ListList.TextPostGre_SQL.Click("24;6");
            Delay.Milliseconds(2510);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm1.TextUpdateQuery' at 29;8.", repo.WebDocumentLocalhost_8888.FormForm1.TextUpdateQueryInfo, new RecordItemIndex(28));
            repo.WebDocumentLocalhost_8888.FormForm1.TextUpdateQuery.Click("29;8");
            Delay.Milliseconds(800);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'UPDATE Test_Src set STATUS='CLOSED'' with focus on 'WebDocumentLocalhost_8888.FormForm1.TextUpdateQuery'.", repo.WebDocumentLocalhost_8888.FormForm1.TextUpdateQueryInfo, new RecordItemIndex(29));
            repo.WebDocumentLocalhost_8888.FormForm1.TextUpdateQuery.PressKeys("UPDATE Test_Src set STATUS='CLOSED'");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm1.TextReadSize' at 24;7.", repo.WebDocumentLocalhost_8888.FormForm1.TextReadSizeInfo, new RecordItemIndex(30));
            repo.WebDocumentLocalhost_8888.FormForm1.TextReadSize.Click("24;7");
            Delay.Milliseconds(490);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1 down}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}' with focus on 'WebDocumentLocalhost_8888.FormForm1.TextReadSize'.", repo.WebDocumentLocalhost_8888.FormForm1.TextReadSizeInfo, new RecordItemIndex(31));
            repo.WebDocumentLocalhost_8888.FormForm1.TextReadSize.PressKeys("{NumPad1 down}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}");
            Delay.Milliseconds(2150);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 20;6.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(32));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("20;6");
            Delay.Milliseconds(1960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157' at 25;17.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157Info, new RecordItemIndex(33));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157.Click(MouseButtons.Right, "25;17");
            Delay.Milliseconds(1770);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 30;4.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(34));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("30;4");
            Delay.Milliseconds(1440);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2' at 42;9.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2Info, new RecordItemIndex(35));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2.Click("42;9");
            Delay.Milliseconds(2990);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'p' with focus on 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2'.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2Info, new RecordItemIndex(36));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2.PressKeys("p");
            Delay.Milliseconds(520);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'arser' with focus on 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2'.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2Info, new RecordItemIndex(37));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextServiceId2.PressKeys("arser");
            Delay.Milliseconds(1690);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox1.TextTextInput' at 34;12.", repo.WebDocumentLocalhost_8888.ContainerVBox1.TextTextInputInfo, new RecordItemIndex(38));
            repo.WebDocumentLocalhost_8888.ContainerVBox1.TextTextInput.Click("34;12");
            Delay.Milliseconds(1400);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}S{LShiftKey up}ample{LShiftKey down}_{LShiftKey up}typ' with focus on 'WebDocumentLocalhost_8888.ContainerVBox1.ComboBoxSchemaName'.", repo.WebDocumentLocalhost_8888.ContainerVBox1.ComboBoxSchemaNameInfo, new RecordItemIndex(39));
            repo.WebDocumentLocalhost_8888.ContainerVBox1.ComboBoxSchemaName.PressKeys("{LShiftKey down}S{LShiftKey up}ample{LShiftKey down}_{LShiftKey up}typ");
            Delay.Milliseconds(3000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox1.TextTextInput1' at 52;4.", repo.WebDocumentLocalhost_8888.ContainerVBox1.TextTextInput1Info, new RecordItemIndex(40));
            repo.WebDocumentLocalhost_8888.ContainerVBox1.TextTextInput1.Click("52;4");
            Delay.Milliseconds(4660);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox1.ButtonButton2' at 3;10.", repo.WebDocumentLocalhost_8888.ContainerVBox1.ButtonButton2Info, new RecordItemIndex(41));
            repo.WebDocumentLocalhost_8888.ContainerVBox1.ButtonButton2.Click("3;10");
            Delay.Milliseconds(1730);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ListList.TextMessage_id' at 125;3.", repo.WebDocumentLocalhost_8888.ListList.TextMessage_idInfo, new RecordItemIndex(42));
            repo.WebDocumentLocalhost_8888.ListList.TextMessage_id.Click("125;3");
            Delay.Milliseconds(1460);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerHBox2.ButtonButton3' at 7;13.", repo.WebDocumentLocalhost_8888.ContainerHBox2.ButtonButton3Info, new RecordItemIndex(43));
            repo.WebDocumentLocalhost_8888.ContainerHBox2.ButtonButton3.Click("7;13");
            Delay.Milliseconds(1930);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ListList.TextContract_id1' at 95;0.", repo.WebDocumentLocalhost_8888.ListList.TextContract_id1Info, new RecordItemIndex(44));
            repo.WebDocumentLocalhost_8888.ListList.TextContract_id1.Click("95;0");
            Delay.Milliseconds(1960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerHBox1.ButtonButton4' at 17;9.", repo.WebDocumentLocalhost_8888.ContainerHBox1.ButtonButton4Info, new RecordItemIndex(45));
            repo.WebDocumentLocalhost_8888.ContainerHBox1.ButtonButton4.Click("17;9");
            Delay.Milliseconds(1880);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ListList.TextStatus1' at 85;4.", repo.WebDocumentLocalhost_8888.ListList.TextStatus1Info, new RecordItemIndex(46));
            repo.WebDocumentLocalhost_8888.ListList.TextStatus1.Click("85;4");
            Delay.Milliseconds(1630);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox1.Text_02' at 17;14.", repo.WebDocumentLocalhost_8888.ContainerVBox1.Text_02Info, new RecordItemIndex(47));
            repo.WebDocumentLocalhost_8888.ContainerVBox1.Text_02.Click("17;14");
            Delay.Milliseconds(1410);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}MSG' with focus on 'WebDocumentLocalhost_8888.ContainerVBox1.Text_02'.", repo.WebDocumentLocalhost_8888.ContainerVBox1.Text_02Info, new RecordItemIndex(48));
            repo.WebDocumentLocalhost_8888.ContainerVBox1.Text_02.PressKeys("{LShiftKey down}MSG");
            Delay.Milliseconds(1050);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ID{LShiftKey up}' with focus on 'WebDocumentLocalhost_8888.ContainerVBox1.Text_02'.", repo.WebDocumentLocalhost_8888.ContainerVBox1.Text_02Info, new RecordItemIndex(49));
            repo.WebDocumentLocalhost_8888.ContainerVBox1.Text_02.PressKeys("ID{LShiftKey up}");
            Delay.Milliseconds(1770);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerHBox2.Text_12' at 19;10.", repo.WebDocumentLocalhost_8888.ContainerHBox2.Text_12Info, new RecordItemIndex(50));
            repo.WebDocumentLocalhost_8888.ContainerHBox2.Text_12.Click("19;10");
            Delay.Milliseconds(2370);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CNTRACTID' with focus on 'WebDocumentLocalhost_8888.ContainerHBox2.Text_12'.", repo.WebDocumentLocalhost_8888.ContainerHBox2.Text_12Info, new RecordItemIndex(51));
            repo.WebDocumentLocalhost_8888.ContainerHBox2.Text_12.PressKeys("CNTRACTID");
            Delay.Milliseconds(2660);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerHBox1.Text_22' at 13;3.", repo.WebDocumentLocalhost_8888.ContainerHBox1.Text_22Info, new RecordItemIndex(52));
            repo.WebDocumentLocalhost_8888.ContainerHBox1.Text_22.Click("13;3");
            Delay.Milliseconds(2290);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}ST' with focus on 'WebDocumentLocalhost_8888.ContainerHBox1.Text_22'.", repo.WebDocumentLocalhost_8888.ContainerHBox1.Text_22Info, new RecordItemIndex(53));
            repo.WebDocumentLocalhost_8888.ContainerHBox1.Text_22.PressKeys("{LShiftKey down}ST");
            Delay.Milliseconds(1190);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ATUS{LShiftKey up}' with focus on 'WebDocumentLocalhost_8888.ContainerHBox1.Text_22'.", repo.WebDocumentLocalhost_8888.ContainerHBox1.Text_22Info, new RecordItemIndex(54));
            repo.WebDocumentLocalhost_8888.ContainerHBox1.Text_22.PressKeys("ATUS{LShiftKey up}");
            Delay.Milliseconds(2740);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 28;4.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(55));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("28;4");
            Delay.Milliseconds(1830);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051' at 20;18.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051Info, new RecordItemIndex(56));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051.Click(MouseButtons.Right, "20;18");
            Delay.Milliseconds(1650);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 20;0.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(57));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("20;0");
            Delay.Milliseconds(1320);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 63;9.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___Info, new RecordItemIndex(58));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("63;9");
            Delay.Milliseconds(1840);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInput' at 15;6.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInputInfo, new RecordItemIndex(59));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInput.Click("15;6");
            Delay.Milliseconds(2340);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTagFormater' at 50;6.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTagFormaterInfo, new RecordItemIndex(60));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTagFormater.Click("50;6");
            Delay.Milliseconds(1570);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 22;2.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoadInfo, new RecordItemIndex(61));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("22;2");
            Delay.Milliseconds(1960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1' at 86;9.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1Info, new RecordItemIndex(62));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1.Click("86;9");
            Delay.Milliseconds(900);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'formater' with focus on 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1'.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1Info, new RecordItemIndex(63));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId1.PressKeys("formater");
            Delay.Milliseconds(1990);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 28;12.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(64));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("28;12");
            Delay.Milliseconds(2130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_385108' at 29;17.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_385108Info, new RecordItemIndex(65));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_385108.Click(MouseButtons.Right, "29;17");
            Delay.Milliseconds(1840);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 21;11.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(66));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("21;11");
            Delay.Milliseconds(1270);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___' at 50;17.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___Info, new RecordItemIndex(67));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad_template___.Click("50;17");
            Delay.Milliseconds(1690);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInput' at 69;12.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInputInfo, new RecordItemIndex(68));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextTextInput.Click("69;12");
            Delay.Milliseconds(1790);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.FlexObjectIceFish.TextDestinationfile' at 74;7.", repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextDestinationfileInfo, new RecordItemIndex(69));
            repo.WebDocument10_200_41_76_8880.FlexObjectIceFish.TextDestinationfile.Click("74;7");
            Delay.Milliseconds(1830);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad' at 18;8.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoadInfo, new RecordItemIndex(70));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonLoad.Click("18;8");
            Delay.Milliseconds(2410);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId' at 29;8.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceIdInfo, new RecordItemIndex(71));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId.Click("29;8");
            Delay.Milliseconds(770);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'dest' with focus on 'WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId'.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceIdInfo, new RecordItemIndex(72));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.TextServiceId.PressKeys("dest");
            Delay.Milliseconds(1510);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave' at 26;21.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(73));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonSave.Click("26;21");
            Delay.Milliseconds(2130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonRouters' at 18;2.", repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonRoutersInfo, new RecordItemIndex(74));
            repo.WebDocumentLocalhost_8888.ContainerComponent_Palette.ButtonRouters.Click("18;2");
            Delay.Milliseconds(2650);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.ContainerVBox.PictureLine' at 12;13.", repo.WebDocument10_200_41_76_8880.ContainerVBox.PictureLineInfo, new RecordItemIndex(75));
            repo.WebDocument10_200_41_76_8880.ContainerVBox.PictureLine.Click("12;13");
            Delay.Milliseconds(2260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_3153' at 17;25.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_3153Info, new RecordItemIndex(76));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_1_3153.MoveTo("17;25");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2460);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157' at 9;12.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157Info, new RecordItemIndex(77));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157.MoveTo("9;12");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2740);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.ContainerVBox.PictureLine' at 3;10.", repo.WebDocument10_200_41_76_8880.ContainerVBox.PictureLineInfo, new RecordItemIndex(78));
            repo.WebDocument10_200_41_76_8880.ContainerVBox.PictureLine.Click("3;10");
            Delay.Milliseconds(1910);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157' at 19;16.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157Info, new RecordItemIndex(79));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_5_79157.MoveTo("19;16");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2180);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051' at 15;18.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051Info, new RecordItemIndex(80));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051.MoveTo("15;18");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2540);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_41_76_8880.ContainerVBox.PictureLine' at 17;10.", repo.WebDocument10_200_41_76_8880.ContainerVBox.PictureLineInfo, new RecordItemIndex(81));
            repo.WebDocument10_200_41_76_8880.ContainerVBox.PictureLine.Click("17;10");
            Delay.Milliseconds(2730);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051' at 20;28.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051Info, new RecordItemIndex(82));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_9_23051.MoveTo("20;28");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1800);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_385108' at 35;26.", repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_385108Info, new RecordItemIndex(83));
            repo.WebDocumentLocalhost_8888.ContainerGraphCanvas1.PictureIcon_3_385108.MoveTo("35;26");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2380);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.TextNameText' at 59;15.", repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameTextInfo, new RecordItemIndex(84));
            repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameText.Click("59;15");
            Delay.Milliseconds(870);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}B{LShiftKey up}{Back}{LShiftKey down}D' with focus on 'WebDocumentLocalhost_8888.ContainerVBox.TextNameText'.", repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameTextInfo, new RecordItemIndex(85));
            repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameText.PressKeys("{LShiftKey down}B{LShiftKey up}{Back}{LShiftKey down}D");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'B_FILE_' with focus on 'WebDocumentLocalhost_8888.ContainerVBox.TextNameText'.", repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameTextInfo, new RecordItemIndex(86));
            repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameText.PressKeys("B_FILE_");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'P{LShiftKey up}o' with focus on 'WebDocumentLocalhost_8888.ContainerVBox.TextNameText'.", repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameTextInfo, new RecordItemIndex(87));
            repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameText.PressKeys("P{LShiftKey up}o");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'stgres' with focus on 'WebDocumentLocalhost_8888.ContainerVBox.TextNameText'.", repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameTextInfo, new RecordItemIndex(88));
            repo.WebDocumentLocalhost_8888.ContainerVBox.TextNameText.PressKeys("stgres");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxRecovery' at 7;12.", repo.WebDocumentLocalhost_8888.FormForm.CheckBoxRecoveryInfo, new RecordItemIndex(89));
            repo.WebDocumentLocalhost_8888.FormForm.CheckBoxRecovery.Click("7;12");
            Delay.Milliseconds(1330);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxPrcsEvntLog' at 6;7.", repo.WebDocumentLocalhost_8888.FormForm.CheckBoxPrcsEvntLogInfo, new RecordItemIndex(90));
            repo.WebDocumentLocalhost_8888.FormForm.CheckBoxPrcsEvntLog.Click("6;7");
            Delay.Milliseconds(1600);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FormForm.CheckBoxMsgEvntLog' at 6;3.", repo.WebDocumentLocalhost_8888.FormForm.CheckBoxMsgEvntLogInfo, new RecordItemIndex(91));
            repo.WebDocumentLocalhost_8888.FormForm.CheckBoxMsgEvntLog.Click("6;3");
            Delay.Milliseconds(1510);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerHBox.CheckBoxCompEvntLog' at 6;7.", repo.WebDocumentLocalhost_8888.ContainerHBox.CheckBoxCompEvntLogInfo, new RecordItemIndex(92));
            repo.WebDocumentLocalhost_8888.ContainerHBox.CheckBoxCompEvntLog.Click("6;7");
            Delay.Milliseconds(1660);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.ButtonSave1' at 15;5.", repo.WebDocumentLocalhost_8888.ContainerVBox.ButtonSave1Info, new RecordItemIndex(93));
            repo.WebDocumentLocalhost_8888.ContainerVBox.ButtonSave1.Click("15;5");
            Delay.Milliseconds(2600);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK' at 32;16.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOKInfo, new RecordItemIndex(94));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK.Click("32;16");
            Delay.Milliseconds(1840);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.ContainerVBox.ButtonPublish' at 40;6.", repo.WebDocumentLocalhost_8888.ContainerVBox.ButtonPublishInfo, new RecordItemIndex(95));
            repo.WebDocumentLocalhost_8888.ContainerVBox.ButtonPublish.Click("40;6");
            Delay.Milliseconds(2370);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK1' at 35;17.", repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK1Info, new RecordItemIndex(96));
            repo.WebDocumentLocalhost_8888.FlexObjectIceFish.ButtonOK1.Click("35;17");
            Delay.Milliseconds(840);
            
        }

#region Image Feature Data
#endregion
    }
}
