///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace Finetuned
{
    /// <summary>
    /// The Process_File_FIXMLValidator_File_21 recording.
    /// </summary>
    [TestModule("e61654f5-0223-4ac2-b460-50c86d30d0be", ModuleType.Recording, 1)]
    public partial class Process_File_FIXMLValidator_File_21 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PS_File_FIXMLValidator_21 repository.
        /// </summary>
        public static PS_File_FIXMLValidator_21 repo = PS_File_FIXMLValidator_21.Instance;

        static Process_File_FIXMLValidator_File_21 instance = new Process_File_FIXMLValidator_File_21();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Process_File_FIXMLValidator_File_21()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Process_File_FIXMLValidator_File_21 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpoints' at 42;10.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpointsInfo, new RecordItemIndex(0));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpoints.Click("42;10");
            Delay.Milliseconds(2320);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_3' at 11;9.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_3Info, new RecordItemIndex(1));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_3.MoveTo("11;9", 2300);
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(760);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas' at 165;112.", repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvasInfo, new RecordItemIndex(2));
            repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas.MoveTo("165;112");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2510);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonParsers' at 68;8.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonParsersInfo, new RecordItemIndex(3));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonParsers.Click("68;8");
            Delay.Milliseconds(3210);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_30' at 15;16.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_30Info, new RecordItemIndex(4));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_30.MoveTo("15;16");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(3130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas' at 348;158.", repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvasInfo, new RecordItemIndex(5));
            repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas.MoveTo("348;158");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2520);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonServices' at 78;7.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonServicesInfo, new RecordItemIndex(6));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonServices.Click("78;7");
            Delay.Milliseconds(2800);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_34' at 11;18.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_34Info, new RecordItemIndex(7));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_34.MoveTo("11;18");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(3010);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas' at 511;181.", repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvasInfo, new RecordItemIndex(8));
            repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas.MoveTo("511;181");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2350);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonFormatters' at 79;7.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonFormattersInfo, new RecordItemIndex(9));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonFormatters.Click("79;7", 2300);
            Delay.Milliseconds(680);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_31' at 8;16.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_31Info, new RecordItemIndex(10));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_31.MoveTo("8;16", 2300);
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(660);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas' at 666;175.", repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvasInfo, new RecordItemIndex(11));
            repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas.MoveTo("666;175", 2300);
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(620);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpoints' at 26;7.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpointsInfo, new RecordItemIndex(12));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpoints.Click("26;7", 2300);
            Delay.Milliseconds(210);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_3' at 10;17.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_3Info, new RecordItemIndex(13));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_3.MoveTo("10;17", 2210);
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas' at 862;110.", repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvasInfo, new RecordItemIndex(14));
            repo.WebDocumentLocalhost_8082.ContainerVBox.ContainerGraphCanvas.MoveTo("862;110", 2300);
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1630);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonRouters' at 67;8.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonRoutersInfo, new RecordItemIndex(15));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonRouters.Click("67;8");
            Delay.Milliseconds(7020);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine' at 11;8.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(16));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine.MoveTo("11;8");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(740);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine' at 11;8.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(17));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine.MoveTo("11;8");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2270);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_11673' at 22;26.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_11673Info, new RecordItemIndex(18));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_11673.MoveTo("22;26");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1740);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119' at 14;27.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119Info, new RecordItemIndex(19));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119.MoveTo("14;27");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine' at 10;9.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(20));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine.Click("10;9");
            Delay.Milliseconds(2770);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119' at 22;28.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119Info, new RecordItemIndex(21));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119.MoveTo("22;28");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1460);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142' at 21;20.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142Info, new RecordItemIndex(22));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142.MoveTo("21;20");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1370);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine' at 15;8.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(23));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine.Click("15;8");
            Delay.Milliseconds(1490);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142' at 22;28.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142Info, new RecordItemIndex(24));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142.MoveTo("22;28");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1070);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136' at 22;27.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136Info, new RecordItemIndex(25));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136.MoveTo("22;27");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1190);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine' at 11;11.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(26));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine.Click("11;11");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136' at 34;25.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136Info, new RecordItemIndex(27));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136.MoveTo("34;25");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1290);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_81371' at 16;31.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_81371Info, new RecordItemIndex(28));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_81371.MoveTo("16;31");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2580);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.TabPageError_Reporting' at 58;11.", repo.WebDocumentLocalhost_8082.ContainerVBox.TabPageError_ReportingInfo, new RecordItemIndex(29));
            repo.WebDocumentLocalhost_8082.ContainerVBox.TabPageError_Reporting.Click("58;11");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.ButtonButton' at 143;11.", repo.WebDocumentLocalhost_8082.ContainerVBox.ButtonButtonInfo, new RecordItemIndex(30));
            repo.WebDocumentLocalhost_8082.ContainerVBox.ButtonButton.Click("143;11");
            Delay.Milliseconds(1350);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextFILE_ErrReporter' at 93;6.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFILE_ErrReporterInfo, new RecordItemIndex(31));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFILE_ErrReporter.Click("93;6");
            Delay.Milliseconds(650);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.ButtonConfigure' at 44;9.", repo.WebDocumentLocalhost_8082.ContainerVBox.ButtonConfigureInfo, new RecordItemIndex(32));
            repo.WebDocumentLocalhost_8082.ContainerVBox.ButtonConfigure.Click("44;9");
            Delay.Milliseconds(1230);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 56;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(33));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("56;9");
            Delay.Milliseconds(990);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1' at 129;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1Info, new RecordItemIndex(34));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1.Click("129;9");
            Delay.Milliseconds(650);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextFileErrReporter' at 73;6.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFileErrReporterInfo, new RecordItemIndex(35));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFileErrReporter.Click("73;6");
            Delay.Milliseconds(730);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 35;8.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(36));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("35;8");
            Delay.Milliseconds(820);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId' at 65;16.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceIdInfo, new RecordItemIndex(37));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId.Click("65;16");
            Delay.Milliseconds(980);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'f' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceIdInfo, new RecordItemIndex(38));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId.PressKeys("f");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ileerr' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceIdInfo, new RecordItemIndex(39));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId.PressKeys("ileerr");
            Delay.Milliseconds(3390);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 28;6.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(40));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("28;6");
            Delay.Milliseconds(1330);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.TabPageProcess_Properties' at 83;5.", repo.WebDocumentLocalhost_8082.ContainerVBox.TabPageProcess_PropertiesInfo, new RecordItemIndex(41));
            repo.WebDocumentLocalhost_8082.ContainerVBox.TabPageProcess_Properties.Click("83;5");
            Delay.Milliseconds(1190);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_11673' at 19;23.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_11673Info, new RecordItemIndex(42));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_11673.Click(MouseButtons.Right, "19;23");
            Delay.Milliseconds(1240);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 35;4.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(43));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("35;4");
            Delay.Milliseconds(1380);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 59;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(44));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("59;10");
            Delay.Milliseconds(830);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1' at 126;8.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1Info, new RecordItemIndex(45));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1.Click("126;8");
            Delay.Milliseconds(1440);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextSourcefile' at 40;6.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextSourcefileInfo, new RecordItemIndex(46));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextSourcefile.Click("40;6");
            Delay.Milliseconds(550);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 24;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(47));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("24;7");
            Delay.Milliseconds(760);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1' at 33;19.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1Info, new RecordItemIndex(48));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1.Click("33;19");
            Delay.Milliseconds(1620);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'src' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1Info, new RecordItemIndex(49));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1.PressKeys("src");
            Delay.Milliseconds(3480);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 23;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(50));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("23;10");
            Delay.Milliseconds(2910);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119' at 28;32.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119Info, new RecordItemIndex(51));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_30_299119.Click(MouseButtons.Right, "28;32");
            Delay.Milliseconds(2540);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 13;5.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(52));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("13;5");
            Delay.Milliseconds(1940);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 111;11.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(53));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("111;11");
            Delay.Milliseconds(2620);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInput' at 54;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInputInfo, new RecordItemIndex(54));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInput.Click("54;7");
            Delay.Milliseconds(1480);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixmlparser' at 45;8.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixmlparserInfo, new RecordItemIndex(55));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixmlparser.Click("45;8");
            Delay.Milliseconds(1410);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 34;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(56));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("34;9");
            Delay.Milliseconds(2880);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2' at 59;14.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(57));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.Click("59;14");
            Delay.Milliseconds(2020);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'f' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(58));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("f");
            Delay.Milliseconds(630);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ixmlpar' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(59));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("ixmlpar");
            Delay.Milliseconds(4700);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 39;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(60));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("39;10");
            Delay.Milliseconds(2650);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142' at 23;33.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142Info, new RecordItemIndex(61));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_34_462142.Click(MouseButtons.Right, "23;33");
            Delay.Milliseconds(1230);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 15;3.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(62));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("15;3");
            Delay.Milliseconds(2260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3' at 5;8.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3Info, new RecordItemIndex(63));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3.Click("5;8");
            Delay.Milliseconds(1800);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fi' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3Info, new RecordItemIndex(64));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3.PressKeys("fi");
            Delay.Milliseconds(870);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'xml' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3Info, new RecordItemIndex(65));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3.PressKeys("xml");
            Delay.Milliseconds(1930);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'val' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3Info, new RecordItemIndex(66));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3.PressKeys("val");
            Delay.Milliseconds(2580);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 43;15.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(67));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("43;15");
            Delay.Milliseconds(2510);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136' at 24;29.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136Info, new RecordItemIndex(68));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_31_617136.Click(MouseButtons.Right, "24;29");
            Delay.Milliseconds(1300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 15;4.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(69));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("15;4");
            Delay.Milliseconds(2130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 119;12.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(70));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("119;12");
            Delay.Milliseconds(1120);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInput' at 48;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInputInfo, new RecordItemIndex(71));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInput.Click("48;9");
            Delay.Milliseconds(1550);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixmlformater' at 40;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixmlformaterInfo, new RecordItemIndex(72));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixmlformater.Click("40;9");
            Delay.Milliseconds(1460);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 41;8.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(73));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("41;8");
            Delay.Milliseconds(1900);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2' at 19;14.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(74));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.Click("19;14");
            Delay.Milliseconds(1870);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fi' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(75));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("fi");
            Delay.Milliseconds(1120);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'xml' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(76));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("xml");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'for' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(77));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("for");
            Delay.Milliseconds(3770);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 36;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(78));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("36;7");
            Delay.Milliseconds(3620);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_81371' at 13;34.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_81371Info, new RecordItemIndex(79));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_3_81371.Click(MouseButtons.Right, "13;34");
            Delay.Milliseconds(2210);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 212;6.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(80));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("212;6");
            Delay.Milliseconds(2430);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 74;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(81));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("74;9");
            Delay.Milliseconds(2650);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInput' at 94;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInputInfo, new RecordItemIndex(82));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextTextInput.Click("94;9");
            Delay.Milliseconds(1460);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextDestinationfile' at 72;3.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextDestinationfileInfo, new RecordItemIndex(83));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextDestinationfile.Click("72;3");
            Delay.Milliseconds(1740);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 39;5.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(84));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("39;5");
            Delay.Milliseconds(2130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1' at 22;13.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1Info, new RecordItemIndex(85));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1.Click("22;13");
            Delay.Milliseconds(2070);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'dest' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1Info, new RecordItemIndex(86));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1.PressKeys("dest");
            Delay.Milliseconds(4170);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 33;11.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(87));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("33;11");
            Delay.Milliseconds(4630);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.TextNameText' at 138;11.", repo.WebDocumentLocalhost_8082.ContainerVBox.TextNameTextInfo, new RecordItemIndex(88));
            repo.WebDocumentLocalhost_8082.ContainerVBox.TextNameText.Click("138;11");
            Delay.Milliseconds(2490);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'file' with focus on 'WebDocumentLocalhost_8082.ContainerVBox.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerVBox.TextNameTextInfo, new RecordItemIndex(89));
            repo.WebDocumentLocalhost_8082.ContainerVBox.TextNameText.PressKeys("file");
            Delay.Milliseconds(950);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}_{LShiftKey up}' with focus on 'WebDocumentLocalhost_8082.ContainerVBox.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerVBox.TextNameTextInfo, new RecordItemIndex(90));
            repo.WebDocumentLocalhost_8082.ContainerVBox.TextNameText.PressKeys("{LShiftKey down}_{LShiftKey up}");
            Delay.Milliseconds(1160);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '21' with focus on 'WebDocumentLocalhost_8082.ContainerVBox.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerVBox.TextNameTextInfo, new RecordItemIndex(91));
            repo.WebDocumentLocalhost_8082.ContainerVBox.TextNameText.PressKeys("21");
            Delay.Milliseconds(2120);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.TextUITextField' at 71;14.", repo.WebDocumentLocalhost_8082.ContainerVBox.TextUITextFieldInfo, new RecordItemIndex(92));
            repo.WebDocumentLocalhost_8082.ContainerVBox.TextUITextField.Click("71;14");
            Delay.Milliseconds(1260);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'WebDocumentLocalhost_8082.ContainerVBox.TextUITextField'.", repo.WebDocumentLocalhost_8082.ContainerVBox.TextUITextFieldInfo, new RecordItemIndex(93));
            repo.WebDocumentLocalhost_8082.ContainerVBox.TextUITextField.PressKeys("test");
            Delay.Milliseconds(2270);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.CheckBoxRecovery' at 5;5.", repo.WebDocumentLocalhost_8082.ContainerVBox.CheckBoxRecoveryInfo, new RecordItemIndex(94));
            repo.WebDocumentLocalhost_8082.ContainerVBox.CheckBoxRecovery.Click("5;5");
            Delay.Milliseconds(550);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.CheckBoxPrcsEvntLog' at 4;6.", repo.WebDocumentLocalhost_8082.ContainerVBox.CheckBoxPrcsEvntLogInfo, new RecordItemIndex(95));
            repo.WebDocumentLocalhost_8082.ContainerVBox.CheckBoxPrcsEvntLog.Click("4;6");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerVBox.CheckBoxMsgEvntLog' at 5;6.", repo.WebDocumentLocalhost_8082.ContainerVBox.CheckBoxMsgEvntLogInfo, new RecordItemIndex(96));
            repo.WebDocumentLocalhost_8082.ContainerVBox.CheckBoxMsgEvntLog.Click("5;6");
            Delay.Milliseconds(2790);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave1' at 27;4.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave1Info, new RecordItemIndex(97));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave1.Click("27;4");
            Delay.Milliseconds(3160);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK' at 48;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOKInfo, new RecordItemIndex(98));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK.Click("48;10");
            Delay.Milliseconds(2260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonPublish' at 43;2.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonPublishInfo, new RecordItemIndex(99));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonPublish.Click("43;2");
            Delay.Milliseconds(2800);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK1' at 46;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK1Info, new RecordItemIndex(100));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK1.Click("46;10");
            Delay.Milliseconds(880);
            
        }

#region Image Feature Data
#endregion
    }
}
