///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace Finetuned
{
    /// <summary>
    /// The Process_Jms_IBMMQEndpoint_8 recording.
    /// </summary>
    [TestModule("84390e54-bb37-41e8-a144-0e1941e07da2", ModuleType.Recording, 1)]
    public partial class Process_Jms_IBMMQEndpoint_8 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the JmsIBMMQEndpint_8 repository.
        /// </summary>
        public static JmsIBMMQEndpint_8 repo = JmsIBMMQEndpint_8.Instance;

        static Process_Jms_IBMMQEndpoint_8 instance = new Process_Jms_IBMMQEndpoint_8();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Process_Jms_IBMMQEndpoint_8()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Process_Jms_IBMMQEndpoint_8 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpoints' at 78;8.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpointsInfo, new RecordItemIndex(0));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpoints.Click("78;8");
            Delay.Milliseconds(1240);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_2' at 10;15.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_2Info, new RecordItemIndex(1));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_2.MoveTo("10;15");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1880);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas' at 134;121.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvasInfo, new RecordItemIndex(2));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas.MoveTo("134;121");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1410);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonParsers' at 94;7.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonParsersInfo, new RecordItemIndex(3));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonParsers.Click("94;7");
            Delay.Milliseconds(2660);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_7' at 10;11.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_7Info, new RecordItemIndex(4));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_7.MoveTo("10;11");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1010);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas' at 246;172.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvasInfo, new RecordItemIndex(5));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas.MoveTo("246;172");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1180);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonFormatters' at 90;6.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonFormattersInfo, new RecordItemIndex(6));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonFormatters.Click("90;6");
            Delay.Milliseconds(3690);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_10' at 9;17.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_10Info, new RecordItemIndex(7));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_10.MoveTo("9;17");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas' at 364;207.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvasInfo, new RecordItemIndex(8));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas.MoveTo("364;207");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(4990);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpoints' at 70;3.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpointsInfo, new RecordItemIndex(9));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonEndpoints.Click("70;3");
            Delay.Milliseconds(2580);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_41' at 6;11.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_41Info, new RecordItemIndex(10));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureIcon_41.MoveTo("6;11");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2350);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas' at 480;224.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvasInfo, new RecordItemIndex(11));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas.MoveTo("480;224");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(3580);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonRouters' at 64;4.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonRoutersInfo, new RecordItemIndex(12));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.ButtonRouters.Click("64;4");
            Delay.Milliseconds(1570);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine' at 5;7.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(13));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine.Click("5;7");
            Delay.Milliseconds(580);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_2_8582' at 21;22.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_2_8582Info, new RecordItemIndex(14));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_2_8582.MoveTo("21;22");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(850);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133' at 19;24.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133Info, new RecordItemIndex(15));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133.MoveTo("19;24");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1270);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine' at 9;12.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(16));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine.Click("9;12");
            Delay.Milliseconds(1010);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133' at 22;22.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133Info, new RecordItemIndex(17));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133.MoveTo("22;22");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(710);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168' at 16;24.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168Info, new RecordItemIndex(18));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168.MoveTo("16;24");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine' at 8;9.", repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(19));
            repo.WebDocumentLocalhost_8082.ContainerComponent_Palette.PictureLine.Click("8;9");
            Delay.Milliseconds(800);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168' at 22;25.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168Info, new RecordItemIndex(20));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168.MoveTo("22;25");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1020);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_41_431185' at 21;26.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_41_431185Info, new RecordItemIndex(21));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_41_431185.MoveTo("21;26");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1550);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator1.TabPageError_Reporting' at 40;6.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator1.TabPageError_ReportingInfo, new RecordItemIndex(22));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator1.TabPageError_Reporting.Click("40;6");
            Delay.Milliseconds(1120);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator1.ButtonButton' at 139;9.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator1.ButtonButtonInfo, new RecordItemIndex(23));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator1.ButtonButton.Click("139;9");
            Delay.Milliseconds(1100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextJMS_ErrReporter' at 47;5.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextJMS_ErrReporterInfo, new RecordItemIndex(24));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextJMS_ErrReporter.Click("47;5");
            Delay.Milliseconds(840);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator1.ButtonConfigure' at 53;10.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator1.ButtonConfigureInfo, new RecordItemIndex(25));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator1.ButtonConfigure.Click("53;10");
            Delay.Milliseconds(1660);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 74;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(26));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("74;7");
            Delay.Milliseconds(1210);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1' at 129;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1Info, new RecordItemIndex(27));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1.Click("129;7");
            Delay.Milliseconds(1130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextJMSErrReporter' at 56;2.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextJMSErrReporterInfo, new RecordItemIndex(28));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextJMSErrReporter.Click("56;2");
            Delay.Milliseconds(570);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 17;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(29));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("17;10");
            Delay.Milliseconds(730);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId4' at 64;14.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId4Info, new RecordItemIndex(30));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId4.Click("64;14");
            Delay.Milliseconds(570);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'jmserr' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId4'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId4Info, new RecordItemIndex(31));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId4.PressKeys("jmserr");
            Delay.Milliseconds(1860);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 27;11.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(32));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("27;11");
            Delay.Milliseconds(1270);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator1.TabPageProcess_Properties' at 85;5.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator1.TabPageProcess_PropertiesInfo, new RecordItemIndex(33));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator1.TabPageProcess_Properties.Click("85;5");
            Delay.Milliseconds(740);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_2_8582' at 13;20.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_2_8582Info, new RecordItemIndex(34));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_2_8582.Click(MouseButtons.Right, "13;20");
            Delay.Milliseconds(1150);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 25;4.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(35));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("25;4");
            Delay.Milliseconds(1690);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 68;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(36));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("68;7");
            Delay.Milliseconds(760);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1' at 124;4.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1Info, new RecordItemIndex(37));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1.Click("124;4");
            Delay.Milliseconds(1180);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextJmssource' at 53;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextJmssourceInfo, new RecordItemIndex(38));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextJmssource.Click("53;9");
            Delay.Milliseconds(620);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 29;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(39));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("29;7");
            Delay.Milliseconds(1020);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1' at 59;13.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1Info, new RecordItemIndex(40));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1.Click("59;13");
            Delay.Milliseconds(580);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'jmssrc' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1Info, new RecordItemIndex(41));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId1.PressKeys("jmssrc");
            Delay.Milliseconds(2330);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 35;6.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(42));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("35;6");
            Delay.Milliseconds(1130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133' at 19;23.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133Info, new RecordItemIndex(43));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_7_197133.Click(MouseButtons.Right, "19;23");
            Delay.Milliseconds(1510);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 31;5.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(44));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("31;5");
            Delay.Milliseconds(1330);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 72;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(45));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("72;7");
            Delay.Milliseconds(1120);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1' at 110;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1Info, new RecordItemIndex(46));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1.Click("110;7");
            Delay.Milliseconds(960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixlenparser' at 60;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixlenparserInfo, new RecordItemIndex(47));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixlenparser.Click("60;7");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 26;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(48));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("26;10");
            Delay.Milliseconds(960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2' at 63;11.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(49));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.Click("63;11");
            Delay.Milliseconds(440);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fixl' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(50));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("fixl");
            Delay.Milliseconds(1420);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'e' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(51));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("e");
            Delay.Milliseconds(1020);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'n' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(52));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("n");
            Delay.Milliseconds(630);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'par' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(53));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("par");
            Delay.Milliseconds(1940);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 26;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(54));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("26;7");
            Delay.Milliseconds(1010);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168' at 18;24.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168Info, new RecordItemIndex(55));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_10_315168.Click(MouseButtons.Right, "18;24");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 25;6.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(56));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("25;6");
            Delay.Milliseconds(1130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 57;6.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(57));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("57;6");
            Delay.Milliseconds(1350);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1' at 125;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1Info, new RecordItemIndex(58));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1.Click("125;9");
            Delay.Milliseconds(730);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixlenformater' at 70;6.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixlenformaterInfo, new RecordItemIndex(59));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextFixlenformater.Click("70;6");
            Delay.Milliseconds(880);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 24;11.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(60));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("24;11");
            Delay.Milliseconds(990);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2' at 66;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(61));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.Click("66;10");
            Delay.Milliseconds(370);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fixl' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(62));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("fixl");
            Delay.Milliseconds(1380);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'en' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(63));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("en");
            Delay.Milliseconds(730);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'formatt' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2Info, new RecordItemIndex(64));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId2.PressKeys("formatt");
            Delay.Milliseconds(2340);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 32;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(65));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("32;9");
            Delay.Milliseconds(1600);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_41_431185' at 20;23.", repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_41_431185Info, new RecordItemIndex(66));
            repo.WebDocumentLocalhost_8082.ContainerGraphCanvas1.PictureIcon_41_431185.Click(MouseButtons.Right, "20;23");
            Delay.Milliseconds(1080);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 42;5.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(67));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("42;5");
            Delay.Milliseconds(1270);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___' at 62;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___Info, new RecordItemIndex(68));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad_template___.Click("62;9");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1' at 110;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1Info, new RecordItemIndex(69));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonButton1.Click("110;9");
            Delay.Milliseconds(1630);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextIBMMQ_Dest' at 53;7.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextIBMMQ_DestInfo, new RecordItemIndex(70));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextIBMMQ_Dest.Click("53;7");
            Delay.Milliseconds(960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad' at 29;12.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoadInfo, new RecordItemIndex(71));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonLoad.Click("29;12");
            Delay.Milliseconds(980);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3' at 57;11.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3Info, new RecordItemIndex(72));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3.Click("57;11");
            Delay.Milliseconds(580);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ibmm' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3Info, new RecordItemIndex(73));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3.PressKeys("ibmm");
            Delay.Milliseconds(1670);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'q' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3Info, new RecordItemIndex(74));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3.PressKeys("q");
            Delay.Milliseconds(470);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'dest' with focus on 'WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3'.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3Info, new RecordItemIndex(75));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.TextServiceId3.PressKeys("dest");
            Delay.Milliseconds(2060);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave' at 29;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSaveInfo, new RecordItemIndex(76));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave.Click("29;9");
            Delay.Milliseconds(1800);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText' at 69;12.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameTextInfo, new RecordItemIndex(77));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText.Click("69;12");
            Delay.Milliseconds(2290);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'jms' with focus on 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameTextInfo, new RecordItemIndex(78));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText.PressKeys("jms");
            Delay.Milliseconds(1070);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}_{RShiftKey up}' with focus on 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameTextInfo, new RecordItemIndex(79));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText.PressKeys("{RShiftKey down}_{RShiftKey up}");
            Delay.Milliseconds(1340);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ibmm' with focus on 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameTextInfo, new RecordItemIndex(80));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText.PressKeys("ibmm");
            Delay.Milliseconds(1470);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'q' with focus on 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameTextInfo, new RecordItemIndex(81));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText.PressKeys("q");
            Delay.Milliseconds(880);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}_{RShiftKey up}' with focus on 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameTextInfo, new RecordItemIndex(82));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText.PressKeys("{RShiftKey down}_{RShiftKey up}");
            Delay.Milliseconds(1850);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '8' with focus on 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText'.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameTextInfo, new RecordItemIndex(83));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextNameText.PressKeys("8");
            Delay.Milliseconds(1160);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextUITextField' at 74;14.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextUITextFieldInfo, new RecordItemIndex(84));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextUITextField.Click("74;14");
            Delay.Milliseconds(290);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test8' with focus on 'WebDocumentLocalhost_8082.ContainerTabNavigator.TextUITextField'.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextUITextFieldInfo, new RecordItemIndex(85));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.TextUITextField.PressKeys("test8");
            Delay.Milliseconds(530);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxRecovery' at 4;8.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxRecoveryInfo, new RecordItemIndex(86));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxRecovery.Click("4;8");
            Delay.Milliseconds(930);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxPrcsEvntLog' at 4;5.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxPrcsEvntLogInfo, new RecordItemIndex(87));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxPrcsEvntLog.Click("4;5");
            Delay.Milliseconds(1740);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxMsgEvntLog' at 5;7.", repo.WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxMsgEvntLogInfo, new RecordItemIndex(88));
            repo.WebDocumentLocalhost_8082.ContainerTabNavigator.CheckBoxMsgEvntLog.Click("5;7");
            Delay.Milliseconds(1330);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave1' at 26;12.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave1Info, new RecordItemIndex(89));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonSave1.Click("26;12");
            Delay.Milliseconds(2960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK' at 27;8.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOKInfo, new RecordItemIndex(90));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK.Click("27;8");
            Delay.Milliseconds(1180);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonPublish' at 33;10.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonPublishInfo, new RecordItemIndex(91));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonPublish.Click("33;10");
            Delay.Milliseconds(3130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK1' at 28;9.", repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK1Info, new RecordItemIndex(92));
            repo.WebDocumentLocalhost_8082.FlexObjectTeevra.ButtonOK1.Click("28;9");
            Delay.Milliseconds(770);
            
        }

#region Image Feature Data
#endregion
    }
}
