///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace Finetuned
{
    /// <summary>
    /// The Recording25 recording.
    /// </summary>
    [TestModule("4609f062-8b90-4627-873a-d4735e0b9d28", ModuleType.Recording, 1)]
    public partial class Recording25 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Project25Repository repository.
        /// </summary>
        public static Project25Repository repo = Project25Repository.Instance;

        static Recording25 instance = new Recording25();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording25()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording25 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 75;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 4.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentLocalhost_8080.ContainerComponent_Palette.ButtonEndpoints' at 72;8.", repo.WebDocumentLocalhost_8080.ContainerComponent_Palette.ButtonEndpointsInfo, new RecordItemIndex(0));
            repo.WebDocumentLocalhost_8080.ContainerComponent_Palette.ButtonEndpoints.Click("72;8");
            Delay.Milliseconds(790);
            
            records25();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
}
