///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace Finetuned
{
    /// <summary>
    /// The Recording17 recording.
    /// </summary>
    [TestModule("918d514c-90e5-47cd-a2b8-3114e8d2a87a", ModuleType.Recording, 1)]
    public partial class Recording17 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Project17Repository repository.
        /// </summary>
        public static Project17Repository repo = Project17Repository.Instance;

        static Recording17 instance = new Recording17();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording17()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording17 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.FlexObjectIceFish.ButtonEndpoints' at 66;9.", repo.WebDocumentIceFish.FlexObjectIceFish.ButtonEndpointsInfo, new RecordItemIndex(0));
            repo.WebDocumentIceFish.FlexObjectIceFish.ButtonEndpoints.Click("66;9");
            Delay.Milliseconds(840);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_3' at Center.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_3Info, new RecordItemIndex(1));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_3.MoveTo();
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1290);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas' at 113;55.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvasInfo, new RecordItemIndex(2));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas.MoveTo("113;55");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1070);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'F11' Press.", new RecordItemIndex(3));
            Keyboard.Press(Keys.F11, 87, Keyboard.DefaultKeyPressTime, 1, false);
            Delay.Milliseconds(1300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonParsers' at 64;11.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonParsersInfo, new RecordItemIndex(4));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonParsers.Click("64;11");
            Delay.Milliseconds(2120);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_6' at 5;9.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_6Info, new RecordItemIndex(5));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_6.MoveTo("5;9");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(1680);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas' at 92;154.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvasInfo, new RecordItemIndex(6));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas.MoveTo("92;154");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(3510);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonFormatters' at 93;7.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonFormattersInfo, new RecordItemIndex(7));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonFormatters.Click("93;7");
            Delay.Milliseconds(2510);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_9' at 7;9.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_9Info, new RecordItemIndex(8));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_9.MoveTo("7;9");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2320);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas' at 382;136.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvasInfo, new RecordItemIndex(9));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas.MoveTo("382;136");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1710);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonServices' at 78;6.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonServicesInfo, new RecordItemIndex(10));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonServices.Click("78;6");
            Delay.Milliseconds(1760);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_12' at 8;9.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_12Info, new RecordItemIndex(11));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_12.MoveTo("8;9");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(2050);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas' at 219;120.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvasInfo, new RecordItemIndex(12));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas.MoveTo("219;120");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2820);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonEndpoints' at 63;10.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonEndpointsInfo, new RecordItemIndex(13));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonEndpoints.Click("63;10");
            Delay.Milliseconds(2050);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_3' at 5;12.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_3Info, new RecordItemIndex(14));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureIcon_3.MoveTo("5;12");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(3450);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas' at 486;76.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvasInfo, new RecordItemIndex(15));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas.MoveTo("486;76");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(2260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonRouters' at 72;5.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonRoutersInfo, new RecordItemIndex(16));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.ButtonRouters.Click("72;5");
            Delay.Milliseconds(1430);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLine' at 12;7.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(17));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLine.Click("12;7");
            Delay.Milliseconds(1100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_6416' at 23;35.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_6416Info, new RecordItemIndex(18));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_6416.MoveTo("23;35");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(660);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115' at 37;19.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115Info, new RecordItemIndex(19));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115.MoveTo("37;19");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1180);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLine' at 10;9.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(20));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLine.Click("10;9");
            Delay.Milliseconds(440);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115' at 29;19.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115Info, new RecordItemIndex(21));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115.MoveTo("29;19");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(710);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081' at 24;27.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081Info, new RecordItemIndex(22));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081.MoveTo("24;27");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1600);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLine' at 9;6.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(23));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLine.Click("9;6");
            Delay.Milliseconds(900);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081' at 26;24.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081Info, new RecordItemIndex(24));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081.MoveTo("26;24");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(900);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397' at 10;21.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397Info, new RecordItemIndex(25));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397.MoveTo("10;21");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(1990);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLine' at 14;7.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLineInfo, new RecordItemIndex(26));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerComponent_Palette.PictureLine.Click("14;7");
            Delay.Milliseconds(900);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397' at 29;18.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397Info, new RecordItemIndex(27));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397.MoveTo("29;18");
            Mouse.ButtonDown(MouseButtons.Left);
            Delay.Milliseconds(900);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_43737' at 16;29.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_43737Info, new RecordItemIndex(28));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_43737.MoveTo("16;29");
            Mouse.ButtonUp(MouseButtons.Left);
            Delay.Milliseconds(3260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_6416' at 16;16.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_6416Info, new RecordItemIndex(29));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_6416.Click(MouseButtons.Right, "16;16");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 23;6.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(30));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("23;6");
            Delay.Milliseconds(880);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___' at 30;7.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___Info, new RecordItemIndex(31));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___.Click("30;7");
            Delay.Milliseconds(1130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton' at 128;13.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButtonInfo, new RecordItemIndex(32));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton.Click("128;13");
            Delay.Milliseconds(1070);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextSourcefile' at 72;7.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextSourcefileInfo, new RecordItemIndex(33));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextSourcefile.Click("72;7");
            Delay.Milliseconds(850);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad' at 36;10.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoadInfo, new RecordItemIndex(34));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad.Click("36;10");
            Delay.Milliseconds(1260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId' at 35;15.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceIdInfo, new RecordItemIndex(35));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId.Click("35;15");
            Delay.Milliseconds(240);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'S' Press.", new RecordItemIndex(36));
            Keyboard.Press(Keys.S, 31, Keyboard.DefaultKeyPressTime, 1, false);
            Delay.Milliseconds(580);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ource'.", new RecordItemIndex(37));
            Keyboard.Press("ource");
            Delay.Milliseconds(2320);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave' at 36;12.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(38));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave.Click("36;12");
            Delay.Milliseconds(1440);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115' at 20;20.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115Info, new RecordItemIndex(39));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_6_43115.Click(MouseButtons.Right, "20;20");
            Delay.Milliseconds(870);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 24;5.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(40));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("24;5");
            Delay.Milliseconds(960);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___' at 87;11.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___Info, new RecordItemIndex(41));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___.Click("87;11");
            Delay.Milliseconds(1480);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton' at Center.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButtonInfo, new RecordItemIndex(42));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton.Click();
            Delay.Milliseconds(2190);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.FlexObjectIceFish.TextTextInput' at Center.", repo.WebDocumentIceFish.FlexObjectIceFish.TextTextInputInfo, new RecordItemIndex(43));
            repo.WebDocumentIceFish.FlexObjectIceFish.TextTextInput.Click();
            Delay.Milliseconds(1180);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.FlexObjectIceFish.TextTextInput' at Center.", repo.WebDocumentIceFish.FlexObjectIceFish.TextTextInputInfo, new RecordItemIndex(44));
            repo.WebDocumentIceFish.FlexObjectIceFish.TextTextInput.Click();
            Delay.Milliseconds(1290);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextParserfile' at Center.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextParserfileInfo, new RecordItemIndex(45));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextParserfile.Click();
            Delay.Milliseconds(880);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad' at Center.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoadInfo, new RecordItemIndex(46));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad.Click();
            Delay.Milliseconds(800);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId1' at 94;9.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId1Info, new RecordItemIndex(47));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId1.Click("94;9");
            Delay.Milliseconds(680);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'parser'.", new RecordItemIndex(48));
            Keyboard.Press("parser");
            Delay.Milliseconds(3110);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave' at Center.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(49));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave.Click();
            Delay.Milliseconds(1460);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081' at 22;19.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081Info, new RecordItemIndex(50));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_12_17081.Click(MouseButtons.Right, "22;19");
            Delay.Milliseconds(1130);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 21;7.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(51));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("21;7");
            Delay.Milliseconds(2400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___' at 112;7.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___Info, new RecordItemIndex(52));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___.Click("112;7");
            Delay.Milliseconds(1150);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton' at Center.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButtonInfo, new RecordItemIndex(53));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton.Click();
            Delay.Milliseconds(3930);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextTempisnotnull' at Center.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextTempisnotnullInfo, new RecordItemIndex(54));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextTempisnotnull.Click();
            Delay.Milliseconds(900);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad' at Center.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoadInfo, new RecordItemIndex(55));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad.Click();
            Delay.Milliseconds(1580);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId2' at 114;9.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId2Info, new RecordItemIndex(56));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId2.Click("114;9");
            Delay.Milliseconds(1990);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tempisnotnull'.", new RecordItemIndex(57));
            Keyboard.Press("tempisnotnull");
            Delay.Milliseconds(3480);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave' at 45;6.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(58));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave.Click("45;6");
            Delay.Milliseconds(1990);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397' at 13;23.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397Info, new RecordItemIndex(59));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_9_33397.Click(MouseButtons.Right, "13;23");
            Delay.Milliseconds(1100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 24;10.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(60));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("24;10");
            Delay.Milliseconds(930);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___' at 112;5.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___Info, new RecordItemIndex(61));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___.Click("112;5");
            Delay.Milliseconds(880);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton' at 110;12.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButtonInfo, new RecordItemIndex(62));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton.Click("110;12");
            Delay.Milliseconds(630);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextTagFormater' at 66;9.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextTagFormaterInfo, new RecordItemIndex(63));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextTagFormater.Click("66;9");
            Delay.Milliseconds(540);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad' at 35;7.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoadInfo, new RecordItemIndex(64));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad.Click("35;7");
            Delay.Milliseconds(730);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId1' at 103;12.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId1Info, new RecordItemIndex(65));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId1.Click("103;12");
            Delay.Milliseconds(630);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tagfor'.", new RecordItemIndex(66));
            Keyboard.Press("tagfor");
            Delay.Milliseconds(2000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave' at 42;10.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(67));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave.Click("42;10");
            Delay.Milliseconds(1410);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_43737' at 20;20.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_43737Info, new RecordItemIndex(68));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerGraphCanvas1.PictureIcon_3_43737.Click(MouseButtons.Right, "20;20");
            Delay.Milliseconds(1410);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 21;5.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(69));
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("21;5");
            Delay.Milliseconds(1240);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___' at 83;11.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___Info, new RecordItemIndex(70));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad_template___.Click("83;11");
            Delay.Milliseconds(1040);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton' at 132;12.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButtonInfo, new RecordItemIndex(71));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonButton.Click("132;12");
            Delay.Milliseconds(3400);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextDestinationfile' at 88;11.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextDestinationfileInfo, new RecordItemIndex(72));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextDestinationfile.Click("88;11");
            Delay.Milliseconds(1080);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad' at 24;14.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoadInfo, new RecordItemIndex(73));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonLoad.Click("24;14");
            Delay.Milliseconds(1260);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId' at 53;13.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceIdInfo, new RecordItemIndex(74));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.TextServiceId.Click("53;13");
            Delay.Milliseconds(1130);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'destination'.", new RecordItemIndex(75));
            Keyboard.Press("destination");
            Delay.Milliseconds(4080);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave' at 43;8.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSaveInfo, new RecordItemIndex(76));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonSave.Click("43;8");
            Delay.Milliseconds(1900);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerVBox.TextNameText' at 87;9.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerVBox.TextNameTextInfo, new RecordItemIndex(77));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerVBox.TextNameText.Click("87;9");
            Delay.Milliseconds(960);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'file{RShiftKey down}_{RShiftKey up}'.", new RecordItemIndex(78));
            Keyboard.Press("file{RShiftKey down}_{RShiftKey up}");
            Delay.Milliseconds(1780);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'to'.", new RecordItemIndex(79));
            Keyboard.Press("to");
            Delay.Milliseconds(1090);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}_{RShiftKey up}'.", new RecordItemIndex(80));
            Keyboard.Press("{RShiftKey down}_{RShiftKey up}");
            Delay.Milliseconds(1260);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'file'.", new RecordItemIndex(81));
            Keyboard.Press("file");
            Delay.Milliseconds(1440);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Shift+RShiftKey' Down.", new RecordItemIndex(82));
            Keyboard.Down(Keys.RShiftKey, 54, false);
            Delay.Milliseconds(710);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Shift+OemMinus' Down.", new RecordItemIndex(83));
            Keyboard.Down(Keys.OemMinus, 12, false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'RShiftKey' Up.", new RecordItemIndex(84));
            Keyboard.Up(Keys.RShiftKey, 54, false);
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'OemMinus' Up.", new RecordItemIndex(85));
            Keyboard.Up(Keys.OemMinus, 12, false);
            Delay.Milliseconds(1820);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'T' Press.", new RecordItemIndex(86));
            Keyboard.Press(Keys.T, 20, Keyboard.DefaultKeyPressTime, 1, false);
            Delay.Milliseconds(970);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'empnotnull'.", new RecordItemIndex(87));
            Keyboard.Press("empnotnull");
            Delay.Milliseconds(2420);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerVBox.TextUITextField' at 84;14.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerVBox.TextUITextFieldInfo, new RecordItemIndex(88));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerVBox.TextUITextField.Click("84;14");
            Delay.Milliseconds(350);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test'.", new RecordItemIndex(89));
            Keyboard.Press("test");
            Delay.Milliseconds(1580);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxRecovery' at 6;9.", repo.WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxRecoveryInfo, new RecordItemIndex(90));
            repo.WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxRecovery.Click("6;9");
            Delay.Milliseconds(570);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxPrcsEvntLog' at 5;10.", repo.WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxPrcsEvntLogInfo, new RecordItemIndex(91));
            repo.WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxPrcsEvntLog.Click("5;10");
            Delay.Milliseconds(740);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxMsgEvntLog' at 6;7.", repo.WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxMsgEvntLogInfo, new RecordItemIndex(92));
            repo.WebDocumentHashappEq6c9f023_selecte.FormForm.CheckBoxMsgEvntLog.Click("6;7");
            Delay.Milliseconds(1290);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerVBox.ButtonSave1' at 21;18.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerVBox.ButtonSave1Info, new RecordItemIndex(93));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerVBox.ButtonSave1.Click("21;18");
            Delay.Milliseconds(1870);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonOK' at 21;8.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonOKInfo, new RecordItemIndex(94));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonOK.Click("21;8");
            Delay.Milliseconds(1050);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.ContainerVBox.ButtonPublish' at 33;10.", repo.WebDocumentHashappEq6c9f023_selecte.ContainerVBox.ButtonPublishInfo, new RecordItemIndex(95));
            repo.WebDocumentHashappEq6c9f023_selecte.ContainerVBox.ButtonPublish.Click("33;10");
            Delay.Milliseconds(1850);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonOK1' at 19;8.", repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonOK1Info, new RecordItemIndex(96));
            repo.WebDocumentHashappEq6c9f023_selecte.FlexObjectIceFish.ButtonOK1.Click("19;8");
            Delay.Milliseconds(770);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.FlexObjectIceFish.TextProcess_Modeling_' at 24;5.", repo.WebDocumentIceFish.FlexObjectIceFish.TextProcess_Modeling_Info, new RecordItemIndex(97));
            repo.WebDocumentIceFish.FlexObjectIceFish.TextProcess_Modeling_.Click("24;5");
            Delay.Milliseconds(800);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.FlexObjectIceFish.MenuItemView_Process' at 48;4.", repo.WebDocumentIceFish.FlexObjectIceFish.MenuItemView_ProcessInfo, new RecordItemIndex(98));
            repo.WebDocumentIceFish.FlexObjectIceFish.MenuItemView_Process.Click("48;4");
            Delay.Milliseconds(1690);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIceFish.FlexObjectIceFish.ButtonNew' at 17;14.", repo.WebDocumentIceFish.FlexObjectIceFish.ButtonNewInfo, new RecordItemIndex(99));
            repo.WebDocumentIceFish.FlexObjectIceFish.ButtonNew.Click("17;14");
            Delay.Milliseconds(760);
            
        }

#region Image Feature Data
#endregion
    }
}
