/* Generated by Xgen from: E60_baseline on: 2002-02-12 17:59 */
/*******************************************************************************
* 2002 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   EntHistRptReq.hxx
*
*  DESCRIPTION: see documentation
*
*******************************************************************************/

#ifndef _ENTHISTRPTREQ_HXX_
#define _ENTHISTRPTREQ_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>


/******************************************************************************/

#ifndef _BSC_ENT_HIST_RPT_REQ_REQUEST_T_
#define _BSC_ENT_HIST_RPT_REQ_REQUEST_T_

typedef struct bscEntHistRptReqRequestTag
{
  char prodId[PROD_ID_LEN];
} bscEntHistRptReqRequestT, *pBscEntHistRptReqRequestT;


#endif  /* _BSC_ENT_HIST_RPT_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _EXT_ENT_HIST_RPT_REQ_REQUEST_T_
#define _EXT_ENT_HIST_RPT_REQ_REQUEST_T_

typedef struct extEntHistRptReqRequestTag
{
  char rptIdCod[DRIV_RPT_ID_COD_LEN];
  char locCod;
  char stdRptReqInd;
  char rawRptReqInd;
  char histRptDat[DRIV_DATE_LEN];
} extEntHistRptReqRequestT, *pExtEntHistRptReqRequestT;


#endif  /* _EXT_ENT_HIST_RPT_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _ENT_HIST_RPT_REQ_REQUEST_T_
#define _ENT_HIST_RPT_REQ_REQUEST_T_

typedef struct entHistRptReqRequestTag
{
  dataHeaderT header;
  bscEntHistRptReqRequestT basic;
  extEntHistRptReqRequestT extension;
} entHistRptReqRequestT, *pEntHistRptReqRequestT;


#endif  /* _ENT_HIST_RPT_REQ_REQUEST_T_ */

/******************************************************************************/

#ifndef _ENT_HIST_RPT_REQ_RESPONSE_T_
#define _ENT_HIST_RPT_REQ_RESPONSE_T_

typedef struct entHistRptReqResponseTag
{
  dataHeaderT header;
} entHistRptReqResponseT, *pEntHistRptReqResponseT;


#endif  /* _ENT_HIST_RPT_REQ_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _ENTHISTRPTREQ_HXX_ */

/******************************************************************************/
/* End of file EntHistRptReq.hxx */
/******************************************************************************/
