/* Generated by Xgen from: E61.02.00 on: 2003-03-12 16:09 */
/*******************************************************************************
* 2003 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   ModRptSel.hxx
*
*  DESCRIPTION: see documentation
*
*******************************************************************************/

#ifndef _MODRPTSEL_HXX_
#define _MODRPTSEL_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>


/******************************************************************************/

#ifndef _BSC_MOD_RPT_SEL_REQUEST_T_
#define _BSC_MOD_RPT_SEL_REQUEST_T_

typedef struct bscModRptSelRequestTag
{
  char prodId[PROD_ID_LEN];
  char dateLstUpdDat[DRIV_TIMESTAMP_LEN];
} bscModRptSelRequestT, *pBscModRptSelRequestT;


#endif  /* _BSC_MOD_RPT_SEL_REQUEST_T_ */

/******************************************************************************/

#ifndef _EXT_MOD_RPT_SEL_REQUEST_T_
#define _EXT_MOD_RPT_SEL_REQUEST_T_

typedef struct extModRptSelRequestTag
{
  char rptIdCod[DRIV_RPT_ID_COD_LEN];
  char locCod;
  char stdRptReqInd;
  char rawRptReqInd;
} extModRptSelRequestT, *pExtModRptSelRequestT;


#endif  /* _EXT_MOD_RPT_SEL_REQUEST_T_ */

/******************************************************************************/

#ifndef _MOD_RPT_SEL_REQUEST_T_
#define _MOD_RPT_SEL_REQUEST_T_

typedef struct modRptSelRequestTag
{
  dataHeaderT header;
  bscModRptSelRequestT basic;
  extModRptSelRequestT extension;
} modRptSelRequestT, *pModRptSelRequestT;


#endif  /* _MOD_RPT_SEL_REQUEST_T_ */

/******************************************************************************/

#ifndef _BSC_MOD_RPT_SEL_RESPONSE_T_
#define _BSC_MOD_RPT_SEL_RESPONSE_T_

typedef struct bscModRptSelResponseTag
{
  char dateLstUpdDat[DRIV_TIMESTAMP_LEN];
} bscModRptSelResponseT, *pBscModRptSelResponseT;


#endif  /* _BSC_MOD_RPT_SEL_RESPONSE_T_ */

/******************************************************************************/

#ifndef _MOD_RPT_SEL_RESPONSE_T_
#define _MOD_RPT_SEL_RESPONSE_T_

typedef struct modRptSelResponseTag
{
  dataHeaderT header;
  bscModRptSelResponseT basic;
} modRptSelResponseT, *pModRptSelResponseT;


#endif  /* _MOD_RPT_SEL_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _MODRPTSEL_HXX_ */

/******************************************************************************/
/* End of file ModRptSel.hxx */
/******************************************************************************/
