/* Generated by Xgen from: E80.01.05 on: 2005-01-14 09:16 */
/*******************************************************************************
* 2005 (c) Copyright Eurex (R) Zuerich AG, Eurex (R) Frankfurt AG
********************************************************************************
*
*  FILE NAME:   StopHrtBeat.hxx
*
*  DESCRIPTION: Layouts used for
*               Stop Heartbeat
*
*******************************************************************************/

#ifndef _STOPHRTBEAT_HXX_
#define _STOPHRTBEAT_HXX_

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

#include <DRIV_common_structs.hxx>
#include <DRIV_data_types.hxx>


/******************************************************************************/

#ifndef _BSC_STOP_HRT_BEAT_REQUEST_T_
#define _BSC_STOP_HRT_BEAT_REQUEST_T_

typedef struct bscStopHrtBeatRequestTag
{
  char quoDelInd;
} bscStopHrtBeatRequestT, *pBscStopHrtBeatRequestT;


#endif  /* _BSC_STOP_HRT_BEAT_REQUEST_T_ */

/******************************************************************************/

#ifndef _STOP_HRT_BEAT_REQUEST_T_
#define _STOP_HRT_BEAT_REQUEST_T_

typedef struct stopHrtBeatRequestTag
{
  dataHeaderT header;
  bscStopHrtBeatRequestT basic;
} stopHrtBeatRequestT, *pStopHrtBeatRequestT;


#endif  /* _STOP_HRT_BEAT_REQUEST_T_ */

/******************************************************************************/

#ifndef _STOP_HRT_BEAT_RESPONSE_T_
#define _STOP_HRT_BEAT_RESPONSE_T_

typedef struct stopHrtBeatResponseTag
{
  dataHeaderT header;
} stopHrtBeatResponseT, *pStopHrtBeatResponseT;


#endif  /* _STOP_HRT_BEAT_RESPONSE_T_ */

/******************************************************************************/

#if defined(__cplusplus) || defined(c_plusplus)
} /* close scope of 'extern "C"' declaration which encloses file. */
#endif

#endif /* _STOPHRTBEAT_HXX_ */

/******************************************************************************/
/* End of file StopHrtBeat.hxx */
/******************************************************************************/
