'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core

Namespace Validation_Creation_templates

	''' <summary>
	''' The Recording1 recording.
	''' </summary>
	Public Partial Class CBR

		Shared Sub New()
			'Your recording specific initialization code goes here.
		End Sub

		Private Sub Init()
			' Your recording specific initialization code goes here.
		End Sub

		Public Sub Mouse_Down_ButtonSave11()
			
			delay.Milliseconds(2000)
			' Your code goes here. Code inside this method will not be changed by the code generator.
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1' at Center.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1Info, new RecordItemIndex(-1))
			repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1.MoveTo()
			Mouse.ButtonDown(MouseButtons.Left)
		End Sub

        Public Shared Property Expression_1() As String  
		    Get  
		        Return Expression1   
		    End Get  
		    Set  
		        Expression1 = Value   
		    End Set  
		End Property  
		Private Shared Expression1 As String 
		Public Shared Sub Key_Shortcut1()
			'Your code here. Code inside this method will not be changed by the code generator.
			Report.Info(Expression1)
			Keyboard.Press(Expression1)
		End Sub

'        Public Sub Key_Shortcut1()
'            ' Your code goes here. Code inside this method will not be changed by the code generator.
'            Report.Log(ReportLevel.Info, "Keyboard", "Key 'E' Press.", new RecordItemIndex(-1))
'            Keyboard.Press(Keys.E, 18, Keyboard.DefaultKeyPressTime, 1, False)
'        End Sub

'        Public Sub Expression1()
'            ' Your code goes here. Code inside this method will not be changed by the code generator.
'            Report.Log(ReportLevel.Info, "Keyboard", "Key 'T' Press.", new RecordItemIndex(-1))
'            Keyboard.Press(Keys.T, 20, Keyboard.DefaultKeyPressTime, 1, False)
'        End Sub

	End Class
End Namespace
