'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing

Namespace Validation_Creation_templates
    ''' <summary>
    ''' The Savepoint recording.
    ''' </summary>
    <TestModule("b4e1c81f-6d59-4b5d-9f90-c7137006b8ab", ModuleType.Recording, 1)> _
    Partial Public Class Savepoint
        Implements ITestModule

        ''' <summary>
        ''' Holds an instance of the Validation_Creation_templatesRepository repository.
        ''' </summary>
        Public Shared repo as Validation_Creation_templatesRepository = Validation_Creation_templatesRepository.Instance

        Shared _instance as Savepoint = new Savepoint()

        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
        End Sub

        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As Savepoint
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub

        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run(Of ITestModule)"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2")> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 100
            Delay.SpeedFactor = 1.0

            Init()

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_123_11_8080.ContainerVBox1.ButtonRouters' at 37;10.", repo.WebDocument10_200_123_11_8080.ContainerVBox1.ButtonRoutersInfo, new RecordItemIndex(0))
            repo.WebDocument10_200_123_11_8080.ContainerVBox1.ButtonRouters.Click("37;10", 100)
            Delay.Milliseconds(1350)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18' at 13;13.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18Info, new RecordItemIndex(1))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18.MoveTo("13;13", 100)
            Mouse.ButtonDown(MouseButtons.Left)
            Delay.Milliseconds(900)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument10_200_123_11_8080.ContainerHBox.ContainerGraphCanvas' at 164;107.", repo.WebDocument10_200_123_11_8080.ContainerHBox.ContainerGraphCanvasInfo, new RecordItemIndex(2))
            repo.WebDocument10_200_123_11_8080.ContainerHBox.ContainerGraphCanvas.MoveTo("164;107", 100)
            Mouse.ButtonUp(MouseButtons.Left)
            Delay.Milliseconds(930)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568' at 12;34.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568Info, new RecordItemIndex(3))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568.Click(MouseButtons.Right, "12;34", 100)
            Delay.Milliseconds(770)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 20;2.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(4))
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("20;2", 100)
            Delay.Milliseconds(120)
                        
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.FormSavepoint_Configuration'.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.FormSavepoint_ConfigurationInfo, new RecordItemIndex(5))
            Validate.Exists(repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.FormSavepoint_ConfigurationInfo)
            Delay.Milliseconds(100)
                        
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Savepoint Configuration') on item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.TextSavepoint_Configuration'.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextSavepoint_ConfigurationInfo, new RecordItemIndex(6))
            Validate.Attribute(repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextSavepoint_ConfigurationInfo, "Text", "Savepoint Configuration")
            Delay.Milliseconds(100)
                        
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save') on item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1'.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1Info, new RecordItemIndex(7))
            Validate.Attribute(repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1Info, "Text", "Save")
            Delay.Milliseconds(100)
                        
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Configure Error Handler...') on item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonConfigure_Error_Handler_'.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonConfigure_Error_Handler_Info, new RecordItemIndex(8))
            Validate.Attribute(repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonConfigure_Error_Handler_Info, "Text", "Configure Error Handler...")
            Delay.Milliseconds(100)
                        
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Cancel') on item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1'.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1Info, new RecordItemIndex(9))
            Validate.Attribute(repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1Info, "Text", "Cancel")
            Delay.Milliseconds(100)
                        
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Service Id') on item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.TextService_Id'.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextService_IdInfo, new RecordItemIndex(10))
            Validate.Attribute(repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextService_IdInfo, "Text", "Service Id")
            Delay.Milliseconds(1490)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3' at 89;12.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3Info, new RecordItemIndex(11))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3.Click("89;12", 100)
            Delay.Milliseconds(1360)
                        
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'SavePoint'.", new RecordItemIndex(12))
            Keyboard.Press("SavePoint")
            Delay.Milliseconds(0)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1' at 43;6.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1Info, new RecordItemIndex(13))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonSave1.Click("43;6", 100)
            Delay.Milliseconds(1190)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568' at 23;31.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568Info, new RecordItemIndex(14))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568.Click(MouseButtons.Right, "23;31", 100)
            Delay.Milliseconds(800)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 15;5.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(15))
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("15;5", 100)
            Delay.Milliseconds(140)
                        
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SavePoint') on item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3'.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3Info, new RecordItemIndex(16))
            Validate.Attribute(repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3Info, "Text", "SavePoint")
            Delay.Milliseconds(470)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3' at 120;13.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3Info, new RecordItemIndex(17))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3.Click("120;13", 100)
            Delay.Milliseconds(940)
                        
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Save'.", new RecordItemIndex(18))
            Keyboard.Press("Save")
            Delay.Milliseconds(390)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1' at 18;8.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1Info, new RecordItemIndex(19))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1.Click("18;8", 100)
            Delay.Milliseconds(1100)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568' at 34;23.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568Info, new RecordItemIndex(20))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.PictureIcon_18_11568.Click(MouseButtons.Right, "34;23", 100)
            Delay.Milliseconds(790)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuIexplore.MenuItemConfigure_Component' at 27;7.", repo.ContextMenuIexplore.MenuItemConfigure_ComponentInfo, new RecordItemIndex(21))
            repo.ContextMenuIexplore.MenuItemConfigure_Component.Click("27;7", 100)
            Delay.Milliseconds(140)
                        
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SavePoint') on item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3'.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3Info, new RecordItemIndex(22))
            Validate.Attribute(repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.TextServiceId3Info, "Text", "SavePoint")
            Delay.Milliseconds(2300)
                        
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1' at 35;9.", repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1Info, new RecordItemIndex(23))
            repo.WebDocument10_200_123_11_8080.FlexObjectIceFish.ButtonCancel1.Click("35;9", 100)
            Delay.Milliseconds(990)
                        
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
