'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core

Namespace UI_TC
	''' <summary>
	''' The Recording2 recording.
	''' </summary>
	Partial Public Class Recording2

		Public Shared repo as Project2Repository = Project2Repository.Instance

		<System.CodeDom.Compiler.GeneratedCode("Ranorex", "2.3.6")> _
		Public Shared Sub Start()
			Mouse.DefaultMoveTime = 300
			Keyboard.DefaultKeyPressTime = 100
			Delay.SpeedFactor = 1.0

			Report.Info("Mouse Left Click item 'WebDocumentHash.FormForm.TextUserIdTextInput' at 60;12.")
			repo.WebDocumentHash.FormForm.TextUserIdTextInput.Click("60;12")
			Delay.Milliseconds(1150)
			Report.Info("Key sequence 'icefish'.")
			Keyboard.Press("icefish")
			Delay.Milliseconds(2550)
			Report.Info("Mouse Left Click item 'WebDocumentHash.FormForm.TextPasswordTextInput' at 49;14.")
			repo.WebDocumentHash.FormForm.TextPasswordTextInput.Click("49;14")
			Delay.Milliseconds(620)
			Report.Info("Key sequence 'icefish'.")
			Keyboard.Press("icefish")
			Delay.Milliseconds(1750)
			Report.Info("Mouse Left Click item 'WebDocumentHash.FormForm.ButtonSubmit' at 39;10.")
			repo.WebDocumentHash.FormForm.ButtonSubmit.Click("39;10", 146)
			Delay.Milliseconds(0)
			Report.Info("Validating AttributeEqual (Caption='Process Modeling ') on item 'WebDocumentHash.ContainerNavigationCanvas.TextProcess_Modeling_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextProcess_Modeling_Info, "Caption", "Process Modeling ")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Text='Process Modeling ') on item 'WebDocumentHash.ContainerNavigationCanvas.TextProcess_Modeling_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextProcess_Modeling_Info, "Text", "Process Modeling ")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Type='Label') on item 'WebDocumentHash.ContainerNavigationCanvas.TextProcess_Modeling_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextProcess_Modeling_Info, "Type", "Label")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Caption='Process Management ') on item 'WebDocumentHash.ContainerNavigationCanvas.TextProcess_Management_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextProcess_Management_Info, "Caption", "Process Management ")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Text='Process Management ') on item 'WebDocumentHash.ContainerNavigationCanvas.TextProcess_Management_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextProcess_Management_Info, "Text", "Process Management ")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Type='Label') on item 'WebDocumentHash.ContainerNavigationCanvas.TextProcess_Management_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextProcess_Management_Info, "Type", "Label")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Visible='True') on item 'WebDocumentHash.ContainerNavigationCanvas.TextMonitoring_Console_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextMonitoring_Console_Info, "Visible", "True")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Caption='Monitoring Console ') on item 'WebDocumentHash.ContainerNavigationCanvas.TextMonitoring_Console_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextMonitoring_Console_Info, "Caption", "Monitoring Console ")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Text='Monitoring Console ') on item 'WebDocumentHash.ContainerNavigationCanvas.TextMonitoring_Console_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextMonitoring_Console_Info, "Text", "Monitoring Console ")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Type='Label') on item 'WebDocumentHash.ContainerNavigationCanvas.TextMonitoring_Console_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextMonitoring_Console_Info, "Type", "Label")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Visible='True') on item 'WebDocumentHash.ContainerNavigationCanvas.TextAdministration_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextAdministration_Info, "Visible", "True")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Caption='Administration ') on item 'WebDocumentHash.ContainerNavigationCanvas.TextAdministration_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextAdministration_Info, "Caption", "Administration ")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Text='Administration ') on item 'WebDocumentHash.ContainerNavigationCanvas.TextAdministration_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextAdministration_Info, "Text", "Administration ")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Type='Label') on item 'WebDocumentHash.ContainerNavigationCanvas.TextAdministration_'.")
			Validate.Attribute(repo.WebDocumentHash.ContainerNavigationCanvas.TextAdministration_Info, "Type", "Label")
			Delay.Milliseconds(100)
		End Sub

#Region "Image Feature Data"
#End Region

	End Class

End Namespace
