'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core

Namespace UI_TC
	''' <summary>
	''' The scenario1 recording.
	''' </summary>
	Partial Public Class scenario1

		Public Shared repo as UI_TCRepository = UI_TCRepository.Instance

		<System.CodeDom.Compiler.GeneratedCode("Ranorex", "2.3.6")> _
		Public Shared Sub Start()
			Mouse.DefaultMoveTime = 300
			Keyboard.DefaultKeyPressTime = 100
			Delay.SpeedFactor = 1.0

			scenario1.startsce1()
			Delay.Milliseconds(0)
			Report.Info("Validating AttributeEqual (Text='User Name') on item 'WebDocumentIceFish1.FormForm.TextUser_Name'.")
			Validate.Attribute(repo.WebDocumentIceFish1.FormForm.TextUser_NameInfo, "Text", "User Name")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Text='Password') on item 'WebDocumentIceFish1.FormForm.TextPassword'.")
			Validate.Attribute(repo.WebDocumentIceFish1.FormForm.TextPasswordInfo, "Text", "Password")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Text='Submit') on item 'WebDocumentIceFish.FormForm.ButtonSubmit'.")
			Validate.Attribute(repo.WebDocumentIceFish.FormForm.ButtonSubmitInfo, "Text", "Submit")
			Delay.Milliseconds(100)
			Report.Info("Validating AttributeEqual (Text='Reset') on item 'WebDocumentIceFish1.FormForm.ButtonReset'.")
			Validate.Attribute(repo.WebDocumentIceFish1.FormForm.ButtonResetInfo, "Text", "Reset")
			Delay.Milliseconds(520)
			Report.Info("Mouse Left Click item 'WebDocumentIceFish.FormForm.TextUserIdTextInput' at 58;8.")
			repo.WebDocumentIceFish.FormForm.TextUserIdTextInput.Click("58;8", 100)
			Delay.Milliseconds(1080)
			scenario1.userid()
			Delay.Milliseconds(0)
			scenario1.pwd()
			Delay.Milliseconds(0)
			scenario1.submit()
			Delay.Milliseconds(0)
			scenario1.pass_fail()
			Delay.Milliseconds(100)
			scenario1.end1()
			Delay.Milliseconds(0)
		End Sub

#Region "Image Feature Data"
#End Region

	End Class

End Namespace
