///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Finetuned
{
    /// <summary>
    /// The class representing the Project41Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.2"), RepositoryFolder("31097da2-1aff-446c-99c8-77ee9da049d7")]
    public partial class Project41Repository : RepoGenBaseFolder
    {
        static Project41Repository instance = new Project41Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Project41Repository element repository.
        /// </summary>
        public static Project41Repository Instance {
            get { return instance; }
        }

        Project41RepositoryFolders.WebDocument10_200_41_76_8888AppFolder _webdocument10_200_41_76_8888;
        Project41RepositoryFolders.ContextMenuIexploreAppFolder _contextmenuiexplore;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Project41Repository() : base("Project41Repository", "", null, 30000, false)
        {
            _webdocument10_200_41_76_8888 = new Project41RepositoryFolders.WebDocument10_200_41_76_8888AppFolder(this);
            _contextmenuiexplore = new Project41RepositoryFolders.ContextMenuIexploreAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The WebDocument10_200_41_76_8888 folder.
        /// </summary>
        [RepositoryFolder("fd46a5d6-33ff-4bb5-afb9-a1f689df7996")]
        public virtual Project41RepositoryFolders.WebDocument10_200_41_76_8888AppFolder WebDocument10_200_41_76_8888
        {
            get { return _webdocument10_200_41_76_8888; }
        }

        /// <summary>
        /// The ContextMenuIexplore folder.
        /// </summary>
        [RepositoryFolder("7da7aa1b-b388-422c-a1e7-c246daf28d41")]
        public virtual Project41RepositoryFolders.ContextMenuIexploreAppFolder ContextMenuIexplore
        {
            get { return _contextmenuiexplore; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class Project41RepositoryFolders
    {
        /// <summary>
        /// The WebDocument10_200_41_76_8888AppFolder folder.
        /// </summary>
        [RepositoryFolder("fd46a5d6-33ff-4bb5-afb9-a1f689df7996")]
        public partial class WebDocument10_200_41_76_8888AppFolder : RepoGenBaseFolder
        {
            Project41RepositoryFolders.ContainerComponent_PaletteFolder _containercomponent_palette;
            Project41RepositoryFolders.ContainerGraphCanvas1Folder _containergraphcanvas1;
            Project41RepositoryFolders.FormFormFolder _formform;
            Project41RepositoryFolders.ContainerVBoxFolder _containervbox;
            Project41RepositoryFolders.FlexObjectIceFishFolder _flexobjecticefish;
            RepoItemInfo _selfInfo;
            RepoItemInfo _containergraphcanvasInfo;

            /// <summary>
            /// Creates a new WebDocument10_200_41_76_8888  folder.
            /// </summary>
            public WebDocument10_200_41_76_8888AppFolder(RepoGenBaseFolder parentFolder) :
                    base("WebDocument10_200_41_76_8888", "/dom[@domain~'^.*']", parentFolder, 30000, false, "fd46a5d6-33ff-4bb5-afb9-a1f689df7996")
            {
                _containercomponent_palette = new Project41RepositoryFolders.ContainerComponent_PaletteFolder(this);
                _containergraphcanvas1 = new Project41RepositoryFolders.ContainerGraphCanvas1Folder(this);
                _formform = new Project41RepositoryFolders.FormFormFolder(this);
                _containervbox = new Project41RepositoryFolders.ContainerVBoxFolder(this);
                _flexobjecticefish = new Project41RepositoryFolders.FlexObjectIceFishFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 30000, null, "fd46a5d6-33ff-4bb5-afb9-a1f689df7996");
                _containergraphcanvasInfo = new RepoItemInfo(this, "ContainerGraphCanvas", "body/flexobject/container/container[@id='mainArea']/container/element/container/container[1]/container[@type='VBox']/container[@id='graphCanvas']", 10000, null, "f42fd312-c523-4e91-af8f-e31a83207402");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd46a5d6-33ff-4bb5-afb9-a1f689df7996")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd46a5d6-33ff-4bb5-afb9-a1f689df7996")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerGraphCanvas item.
            /// </summary>
            [RepositoryItem("f42fd312-c523-4e91-af8f-e31a83207402")]
            public virtual Ranorex.Container ContainerGraphCanvas
            {
                get
                {
                    return _containergraphcanvasInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerGraphCanvas item info.
            /// </summary>
            [RepositoryItemInfo("f42fd312-c523-4e91-af8f-e31a83207402")]
            public virtual RepoItemInfo ContainerGraphCanvasInfo
            {
                get
                {
                    return _containergraphcanvasInfo;
                }
            }

            /// <summary>
            /// The ContainerComponent_Palette folder.
            /// </summary>
            [RepositoryFolder("4f5de4b9-ba36-4be6-a0a0-6c7e6f888a01")]
            public virtual Project41RepositoryFolders.ContainerComponent_PaletteFolder ContainerComponent_Palette
            {
                get { return _containercomponent_palette; }
            }

            /// <summary>
            /// The ContainerGraphCanvas1 folder.
            /// </summary>
            [RepositoryFolder("67f69b75-e4a8-4371-88c0-01e50e6d7de2")]
            public virtual Project41RepositoryFolders.ContainerGraphCanvas1Folder ContainerGraphCanvas1
            {
                get { return _containergraphcanvas1; }
            }

            /// <summary>
            /// The FormForm folder.
            /// </summary>
            [RepositoryFolder("ef837f08-ffdb-47dc-a08d-26387ca0ef2f")]
            public virtual Project41RepositoryFolders.FormFormFolder FormForm
            {
                get { return _formform; }
            }

            /// <summary>
            /// The ContainerVBox folder.
            /// </summary>
            [RepositoryFolder("cf419f79-eee6-4ab4-96eb-5c2956744d08")]
            public virtual Project41RepositoryFolders.ContainerVBoxFolder ContainerVBox
            {
                get { return _containervbox; }
            }

            /// <summary>
            /// The FlexObjectIceFish folder.
            /// </summary>
            [RepositoryFolder("482e3a00-81cf-4ed7-a9f9-1a6074246482")]
            public virtual Project41RepositoryFolders.FlexObjectIceFishFolder FlexObjectIceFish
            {
                get { return _flexobjecticefish; }
            }
        }

        /// <summary>
        /// The ContainerComponent_PaletteFolder folder.
        /// </summary>
        [RepositoryFolder("4f5de4b9-ba36-4be6-a0a0-6c7e6f888a01")]
        public partial class ContainerComponent_PaletteFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonendpointsInfo;
            RepoItemInfo _buttonformattersInfo;
            RepoItemInfo _buttonparsersInfo;
            RepoItemInfo _buttonroutersInfo;
            RepoItemInfo _buttonservicesInfo;
            RepoItemInfo _picturelineInfo;
            RepoItemInfo _pictureicon_12Info;
            RepoItemInfo _pictureicon_9Info;
            RepoItemInfo _pictureicon_6Info;
            RepoItemInfo _pictureicon_3Info;

            /// <summary>
            /// Creates a new ContainerComponent_Palette  folder.
            /// </summary>
            public ContainerComponent_PaletteFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerComponent_Palette", "body/flexobject/container/container[@id='mainArea']/container/element/container/container[1]/container[@caption='Component Palette']", parentFolder, 10000, false, "4f5de4b9-ba36-4be6-a0a0-6c7e6f888a01")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 10000, null, "4f5de4b9-ba36-4be6-a0a0-6c7e6f888a01");
                _buttonendpointsInfo = new RepoItemInfo(this, "ButtonEndpoints", "element[@id='compPalette']/button[@text='Endpoints']", 10000, null, "357cb0c5-9692-4ca2-a920-21bf90760477");
                _buttonformattersInfo = new RepoItemInfo(this, "ButtonFormatters", "element[@id='compPalette']/button[@text='Formatters']", 10000, null, "663c4404-2394-4b49-82c4-cf9d0048016f");
                _buttonparsersInfo = new RepoItemInfo(this, "ButtonParsers", "element[@id='compPalette']/button[@text='Parsers']", 10000, null, "44c6c83f-4b97-4a03-99ff-d776653a75ef");
                _buttonroutersInfo = new RepoItemInfo(this, "ButtonRouters", "element[@id='compPalette']/button[@text='Routers']", 10000, null, "7bcd96e0-47bc-4755-a6b3-aec4eb26c856");
                _buttonservicesInfo = new RepoItemInfo(this, "ButtonServices", "element[@id='compPalette']/button[@text='Services']", 10000, null, "2eb75875-0167-4daa-8a0c-83495343dbf7");
                _picturelineInfo = new RepoItemInfo(this, "PictureLine", "element[@id='compPalette']/element[2]/container[1]/container/picture[@id='line']", 10000, null, "4ed82e57-c580-4a14-b53a-2a5c4c79683d");
                _pictureicon_12Info = new RepoItemInfo(this, "PictureIcon_12", "element[@id='compPalette']/element[3]/container[4]/container[1]/container/container/container/picture[@id='icon_12']", 10000, null, "25d9f665-8b20-4fab-a4fe-8e938b520197");
                _pictureicon_9Info = new RepoItemInfo(this, "PictureIcon_9", "element[@id='compPalette']/element[4]/container[5]/container[1]/container/container/container/picture[@id='icon_9']", 10000, null, "27b2a7ea-6888-43f0-bf71-74fcd2bcd7f9");
                _pictureicon_6Info = new RepoItemInfo(this, "PictureIcon_6", "element[@id='compPalette']/element[5]/container[4]/container[2]/container/container/container/picture[@id='icon_6']", 10000, null, "d32ed3ae-c02d-45f9-98de-c838072cb4cb");
                _pictureicon_3Info = new RepoItemInfo(this, "PictureIcon_3", "element[@id='compPalette']/element[6]/container[4]/container[2]/container/container/container/picture[@id='icon_3']", 10000, null, "5ccd322b-a1e7-4840-bf85-2b29f1107305");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f5de4b9-ba36-4be6-a0a0-6c7e6f888a01")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f5de4b9-ba36-4be6-a0a0-6c7e6f888a01")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonEndpoints item.
            /// </summary>
            [RepositoryItem("357cb0c5-9692-4ca2-a920-21bf90760477")]
            public virtual Ranorex.Button ButtonEndpoints
            {
                get
                {
                    return _buttonendpointsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonEndpoints item info.
            /// </summary>
            [RepositoryItemInfo("357cb0c5-9692-4ca2-a920-21bf90760477")]
            public virtual RepoItemInfo ButtonEndpointsInfo
            {
                get
                {
                    return _buttonendpointsInfo;
                }
            }

            /// <summary>
            /// The ButtonFormatters item.
            /// </summary>
            [RepositoryItem("663c4404-2394-4b49-82c4-cf9d0048016f")]
            public virtual Ranorex.Button ButtonFormatters
            {
                get
                {
                    return _buttonformattersInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFormatters item info.
            /// </summary>
            [RepositoryItemInfo("663c4404-2394-4b49-82c4-cf9d0048016f")]
            public virtual RepoItemInfo ButtonFormattersInfo
            {
                get
                {
                    return _buttonformattersInfo;
                }
            }

            /// <summary>
            /// The ButtonParsers item.
            /// </summary>
            [RepositoryItem("44c6c83f-4b97-4a03-99ff-d776653a75ef")]
            public virtual Ranorex.Button ButtonParsers
            {
                get
                {
                    return _buttonparsersInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonParsers item info.
            /// </summary>
            [RepositoryItemInfo("44c6c83f-4b97-4a03-99ff-d776653a75ef")]
            public virtual RepoItemInfo ButtonParsersInfo
            {
                get
                {
                    return _buttonparsersInfo;
                }
            }

            /// <summary>
            /// The ButtonRouters item.
            /// </summary>
            [RepositoryItem("7bcd96e0-47bc-4755-a6b3-aec4eb26c856")]
            public virtual Ranorex.Button ButtonRouters
            {
                get
                {
                    return _buttonroutersInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonRouters item info.
            /// </summary>
            [RepositoryItemInfo("7bcd96e0-47bc-4755-a6b3-aec4eb26c856")]
            public virtual RepoItemInfo ButtonRoutersInfo
            {
                get
                {
                    return _buttonroutersInfo;
                }
            }

            /// <summary>
            /// The ButtonServices item.
            /// </summary>
            [RepositoryItem("2eb75875-0167-4daa-8a0c-83495343dbf7")]
            public virtual Ranorex.Button ButtonServices
            {
                get
                {
                    return _buttonservicesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonServices item info.
            /// </summary>
            [RepositoryItemInfo("2eb75875-0167-4daa-8a0c-83495343dbf7")]
            public virtual RepoItemInfo ButtonServicesInfo
            {
                get
                {
                    return _buttonservicesInfo;
                }
            }

            /// <summary>
            /// The PictureLine item.
            /// </summary>
            [RepositoryItem("4ed82e57-c580-4a14-b53a-2a5c4c79683d")]
            public virtual Ranorex.Picture PictureLine
            {
                get
                {
                    return _picturelineInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureLine item info.
            /// </summary>
            [RepositoryItemInfo("4ed82e57-c580-4a14-b53a-2a5c4c79683d")]
            public virtual RepoItemInfo PictureLineInfo
            {
                get
                {
                    return _picturelineInfo;
                }
            }

            /// <summary>
            /// The PictureIcon_12 item.
            /// </summary>
            [RepositoryItem("25d9f665-8b20-4fab-a4fe-8e938b520197")]
            public virtual Ranorex.Picture PictureIcon_12
            {
                get
                {
                    return _pictureicon_12Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_12 item info.
            /// </summary>
            [RepositoryItemInfo("25d9f665-8b20-4fab-a4fe-8e938b520197")]
            public virtual RepoItemInfo PictureIcon_12Info
            {
                get
                {
                    return _pictureicon_12Info;
                }
            }

            /// <summary>
            /// The PictureIcon_9 item.
            /// </summary>
            [RepositoryItem("27b2a7ea-6888-43f0-bf71-74fcd2bcd7f9")]
            public virtual Ranorex.Picture PictureIcon_9
            {
                get
                {
                    return _pictureicon_9Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_9 item info.
            /// </summary>
            [RepositoryItemInfo("27b2a7ea-6888-43f0-bf71-74fcd2bcd7f9")]
            public virtual RepoItemInfo PictureIcon_9Info
            {
                get
                {
                    return _pictureicon_9Info;
                }
            }

            /// <summary>
            /// The PictureIcon_6 item.
            /// </summary>
            [RepositoryItem("d32ed3ae-c02d-45f9-98de-c838072cb4cb")]
            public virtual Ranorex.Picture PictureIcon_6
            {
                get
                {
                    return _pictureicon_6Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_6 item info.
            /// </summary>
            [RepositoryItemInfo("d32ed3ae-c02d-45f9-98de-c838072cb4cb")]
            public virtual RepoItemInfo PictureIcon_6Info
            {
                get
                {
                    return _pictureicon_6Info;
                }
            }

            /// <summary>
            /// The PictureIcon_3 item.
            /// </summary>
            [RepositoryItem("5ccd322b-a1e7-4840-bf85-2b29f1107305")]
            public virtual Ranorex.Picture PictureIcon_3
            {
                get
                {
                    return _pictureicon_3Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_3 item info.
            /// </summary>
            [RepositoryItemInfo("5ccd322b-a1e7-4840-bf85-2b29f1107305")]
            public virtual RepoItemInfo PictureIcon_3Info
            {
                get
                {
                    return _pictureicon_3Info;
                }
            }
        }

        /// <summary>
        /// The ContainerGraphCanvas1Folder folder.
        /// </summary>
        [RepositoryFolder("67f69b75-e4a8-4371-88c0-01e50e6d7de2")]
        public partial class ContainerGraphCanvas1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _pictureicon_3_48368Info;
            RepoItemInfo _pictureicon_6_71127Info;
            RepoItemInfo _pictureicon_9_342106Info;
            RepoItemInfo _pictureicon_12_20190Info;
            RepoItemInfo _pictureicon_3_6625Info;

            /// <summary>
            /// Creates a new ContainerGraphCanvas1  folder.
            /// </summary>
            public ContainerGraphCanvas1Folder(RepoGenBaseFolder parentFolder) :
                    base("ContainerGraphCanvas1", "body/flexobject/container/container[@id='mainArea']/container/element/container/container[1]/container[@type='VBox']/container[@id='graphCanvas']", parentFolder, 10000, false, "67f69b75-e4a8-4371-88c0-01e50e6d7de2")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 10000, null, "67f69b75-e4a8-4371-88c0-01e50e6d7de2");
                _pictureicon_3_48368Info = new RepoItemInfo(this, "PictureIcon_3_48368", "container[@id~'^Box.*']/picture[@id='icon_3_48368']", 10000, null, "2a963391-63c4-4a3d-b822-5be17b93b99d");
                _pictureicon_6_71127Info = new RepoItemInfo(this, "PictureIcon_6_71127", "container[@id~'^Box.*']/picture[@id='icon_6_71127']", 10000, null, "66bc6034-4a1c-4822-ab04-6a299eb8cb04");
                _pictureicon_9_342106Info = new RepoItemInfo(this, "PictureIcon_9_342106", "container[@id~'^Box.*']/picture[@id='icon_9_342106']", 10000, null, "f38b7e99-c7d7-485a-9449-1d86588ccb2f");
                _pictureicon_12_20190Info = new RepoItemInfo(this, "PictureIcon_12_20190", "container[@id~'^Box.*']/picture[@id='icon_12_20190']", 10000, null, "3e13fd7f-d7c4-4035-8df3-723bd82dc187");
                _pictureicon_3_6625Info = new RepoItemInfo(this, "PictureIcon_3_6625", "container[@id~'^Box.*']/picture[@id='icon_3_6625']", 10000, null, "a0a870d8-7cfd-4e02-b437-ae635e1b2c70");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("67f69b75-e4a8-4371-88c0-01e50e6d7de2")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("67f69b75-e4a8-4371-88c0-01e50e6d7de2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PictureIcon_3_48368 item.
            /// </summary>
            [RepositoryItem("2a963391-63c4-4a3d-b822-5be17b93b99d")]
            public virtual Ranorex.Picture PictureIcon_3_48368
            {
                get
                {
                    return _pictureicon_3_48368Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_3_48368 item info.
            /// </summary>
            [RepositoryItemInfo("2a963391-63c4-4a3d-b822-5be17b93b99d")]
            public virtual RepoItemInfo PictureIcon_3_48368Info
            {
                get
                {
                    return _pictureicon_3_48368Info;
                }
            }

            /// <summary>
            /// The PictureIcon_6_71127 item.
            /// </summary>
            [RepositoryItem("66bc6034-4a1c-4822-ab04-6a299eb8cb04")]
            public virtual Ranorex.Picture PictureIcon_6_71127
            {
                get
                {
                    return _pictureicon_6_71127Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_6_71127 item info.
            /// </summary>
            [RepositoryItemInfo("66bc6034-4a1c-4822-ab04-6a299eb8cb04")]
            public virtual RepoItemInfo PictureIcon_6_71127Info
            {
                get
                {
                    return _pictureicon_6_71127Info;
                }
            }

            /// <summary>
            /// The PictureIcon_9_342106 item.
            /// </summary>
            [RepositoryItem("f38b7e99-c7d7-485a-9449-1d86588ccb2f")]
            public virtual Ranorex.Picture PictureIcon_9_342106
            {
                get
                {
                    return _pictureicon_9_342106Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_9_342106 item info.
            /// </summary>
            [RepositoryItemInfo("f38b7e99-c7d7-485a-9449-1d86588ccb2f")]
            public virtual RepoItemInfo PictureIcon_9_342106Info
            {
                get
                {
                    return _pictureicon_9_342106Info;
                }
            }

            /// <summary>
            /// The PictureIcon_12_20190 item.
            /// </summary>
            [RepositoryItem("3e13fd7f-d7c4-4035-8df3-723bd82dc187")]
            public virtual Ranorex.Picture PictureIcon_12_20190
            {
                get
                {
                    return _pictureicon_12_20190Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_12_20190 item info.
            /// </summary>
            [RepositoryItemInfo("3e13fd7f-d7c4-4035-8df3-723bd82dc187")]
            public virtual RepoItemInfo PictureIcon_12_20190Info
            {
                get
                {
                    return _pictureicon_12_20190Info;
                }
            }

            /// <summary>
            /// The PictureIcon_3_6625 item.
            /// </summary>
            [RepositoryItem("a0a870d8-7cfd-4e02-b437-ae635e1b2c70")]
            public virtual Ranorex.Picture PictureIcon_3_6625
            {
                get
                {
                    return _pictureicon_3_6625Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureIcon_3_6625 item info.
            /// </summary>
            [RepositoryItemInfo("a0a870d8-7cfd-4e02-b437-ae635e1b2c70")]
            public virtual RepoItemInfo PictureIcon_3_6625Info
            {
                get
                {
                    return _pictureicon_3_6625Info;
                }
            }
        }

        /// <summary>
        /// The FormFormFolder folder.
        /// </summary>
        [RepositoryFolder("ef837f08-ffdb-47dc-a08d-26387ca0ef2f")]
        public partial class FormFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _checkboxmsgevntlogInfo;
            RepoItemInfo _checkboxprcsevntlogInfo;
            RepoItemInfo _checkboxrecoveryInfo;

            /// <summary>
            /// Creates a new FormForm  folder.
            /// </summary>
            public FormFormFolder(RepoGenBaseFolder parentFolder) :
                    base("FormForm", "body/flexobject/container/container[@id='mainArea']/container/element/container/container[1]/container[@type='VBox']/container[@id='processDetails']/element[@id='newProcess']/container/container/container[4]/container[1]/form", parentFolder, 10000, false, "ef837f08-ffdb-47dc-a08d-26387ca0ef2f")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 10000, null, "ef837f08-ffdb-47dc-a08d-26387ca0ef2f");
                _checkboxmsgevntlogInfo = new RepoItemInfo(this, "CheckBoxMsgEvntLog", "container[2]/container/checkbox[@id='msgEvntLog']", 10000, null, "3be5bc2a-5354-4c2e-ae92-d03e4a64aaf5");
                _checkboxprcsevntlogInfo = new RepoItemInfo(this, "CheckBoxPrcsEvntLog", "container[3]/container/checkbox[@id='prcsEvntLog']", 10000, null, "76c4bd90-5686-4218-9fe7-81507e7bf2a5");
                _checkboxrecoveryInfo = new RepoItemInfo(this, "CheckBoxRecovery", "container[4]/container/checkbox[@id='recovery']", 10000, null, "0c3d6928-db01-4388-a9a3-416d90575e4a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ef837f08-ffdb-47dc-a08d-26387ca0ef2f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ef837f08-ffdb-47dc-a08d-26387ca0ef2f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CheckBoxMsgEvntLog item.
            /// </summary>
            [RepositoryItem("3be5bc2a-5354-4c2e-ae92-d03e4a64aaf5")]
            public virtual Ranorex.CheckBox CheckBoxMsgEvntLog
            {
                get
                {
                    return _checkboxmsgevntlogInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBoxMsgEvntLog item info.
            /// </summary>
            [RepositoryItemInfo("3be5bc2a-5354-4c2e-ae92-d03e4a64aaf5")]
            public virtual RepoItemInfo CheckBoxMsgEvntLogInfo
            {
                get
                {
                    return _checkboxmsgevntlogInfo;
                }
            }

            /// <summary>
            /// The CheckBoxPrcsEvntLog item.
            /// </summary>
            [RepositoryItem("76c4bd90-5686-4218-9fe7-81507e7bf2a5")]
            public virtual Ranorex.CheckBox CheckBoxPrcsEvntLog
            {
                get
                {
                    return _checkboxprcsevntlogInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBoxPrcsEvntLog item info.
            /// </summary>
            [RepositoryItemInfo("76c4bd90-5686-4218-9fe7-81507e7bf2a5")]
            public virtual RepoItemInfo CheckBoxPrcsEvntLogInfo
            {
                get
                {
                    return _checkboxprcsevntlogInfo;
                }
            }

            /// <summary>
            /// The CheckBoxRecovery item.
            /// </summary>
            [RepositoryItem("0c3d6928-db01-4388-a9a3-416d90575e4a")]
            public virtual Ranorex.CheckBox CheckBoxRecovery
            {
                get
                {
                    return _checkboxrecoveryInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBoxRecovery item info.
            /// </summary>
            [RepositoryItemInfo("0c3d6928-db01-4388-a9a3-416d90575e4a")]
            public virtual RepoItemInfo CheckBoxRecoveryInfo
            {
                get
                {
                    return _checkboxrecoveryInfo;
                }
            }
        }

        /// <summary>
        /// The ContainerVBoxFolder folder.
        /// </summary>
        [RepositoryFolder("cf419f79-eee6-4ab4-96eb-5c2956744d08")]
        public partial class ContainerVBoxFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _textuitextfieldInfo;
            RepoItemInfo _textnametextInfo;
            RepoItemInfo _buttonpublishInfo;
            RepoItemInfo _buttonsave1Info;

            /// <summary>
            /// Creates a new ContainerVBox  folder.
            /// </summary>
            public ContainerVBoxFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerVBox", "body/flexobject/container/container[@id='mainArea']/container/element/container", parentFolder, 10000, false, "cf419f79-eee6-4ab4-96eb-5c2956744d08")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 10000, null, "cf419f79-eee6-4ab4-96eb-5c2956744d08");
                _textuitextfieldInfo = new RepoItemInfo(this, "TextUITextField", "container[1]/container[@type='VBox']/container[@id='processDetails']/element[@id='newProcess']/container/container/container[4]/container[2]/form/container[1]/text[@id='descriptionText']/text[@caption='']", 10000, null, "eb29167c-baae-4afe-9970-7d6f73d9275a");
                _textnametextInfo = new RepoItemInfo(this, "TextNameText", "container[1]/container[@type='VBox']/container[@id='processDetails']/element[@id='newProcess']/container/container/container[4]/container[2]/form/container[2]/text[@id='nameText']", 10000, null, "938c44a6-9090-431a-8188-0123e04162a7");
                _buttonpublishInfo = new RepoItemInfo(this, "ButtonPublish", "container[2]/button[@id='publishButton']", 10000, null, "a453937f-77e1-45e7-b1c7-13dc0a3cbf71");
                _buttonsave1Info = new RepoItemInfo(this, "ButtonSave1", "container[2]/button[@id='saveButton']", 10000, null, "f362ca3a-cb4c-44d5-a3c2-0ee34af5a11d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf419f79-eee6-4ab4-96eb-5c2956744d08")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf419f79-eee6-4ab4-96eb-5c2956744d08")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextUITextField item.
            /// </summary>
            [RepositoryItem("eb29167c-baae-4afe-9970-7d6f73d9275a")]
            public virtual Ranorex.Text TextUITextField
            {
                get
                {
                    return _textuitextfieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextUITextField item info.
            /// </summary>
            [RepositoryItemInfo("eb29167c-baae-4afe-9970-7d6f73d9275a")]
            public virtual RepoItemInfo TextUITextFieldInfo
            {
                get
                {
                    return _textuitextfieldInfo;
                }
            }

            /// <summary>
            /// The TextNameText item.
            /// </summary>
            [RepositoryItem("938c44a6-9090-431a-8188-0123e04162a7")]
            public virtual Ranorex.Text TextNameText
            {
                get
                {
                    return _textnametextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextNameText item info.
            /// </summary>
            [RepositoryItemInfo("938c44a6-9090-431a-8188-0123e04162a7")]
            public virtual RepoItemInfo TextNameTextInfo
            {
                get
                {
                    return _textnametextInfo;
                }
            }

            /// <summary>
            /// The ButtonPublish item.
            /// </summary>
            [RepositoryItem("a453937f-77e1-45e7-b1c7-13dc0a3cbf71")]
            public virtual Ranorex.Button ButtonPublish
            {
                get
                {
                    return _buttonpublishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonPublish item info.
            /// </summary>
            [RepositoryItemInfo("a453937f-77e1-45e7-b1c7-13dc0a3cbf71")]
            public virtual RepoItemInfo ButtonPublishInfo
            {
                get
                {
                    return _buttonpublishInfo;
                }
            }

            /// <summary>
            /// The ButtonSave1 item.
            /// </summary>
            [RepositoryItem("f362ca3a-cb4c-44d5-a3c2-0ee34af5a11d")]
            public virtual Ranorex.Button ButtonSave1
            {
                get
                {
                    return _buttonsave1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave1 item info.
            /// </summary>
            [RepositoryItemInfo("f362ca3a-cb4c-44d5-a3c2-0ee34af5a11d")]
            public virtual RepoItemInfo ButtonSave1Info
            {
                get
                {
                    return _buttonsave1Info;
                }
            }
        }

        /// <summary>
        /// The FlexObjectIceFishFolder folder.
        /// </summary>
        [RepositoryFolder("482e3a00-81cf-4ed7-a9f9-1a6074246482")]
        public partial class FlexObjectIceFishFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonok1Info;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _textserviceid2Info;
            RepoItemInfo _textserviceid1Info;
            RepoItemInfo _buttonload_template___Info;
            RepoItemInfo _buttonsaveInfo;
            RepoItemInfo _textserviceidInfo;
            RepoItemInfo _buttonloadInfo;
            RepoItemInfo _buttonbuttonInfo;
            RepoItemInfo _textdestinationfileInfo;
            RepoItemInfo _textparserfileInfo;
            RepoItemInfo _textsourcefileInfo;
            RepoItemInfo _texttagformaterInfo;
            RepoItemInfo _texttempintegerInfo;
            RepoItemInfo _indicatorscrollthumbInfo;

            /// <summary>
            /// Creates a new FlexObjectIceFish  folder.
            /// </summary>
            public FlexObjectIceFishFolder(RepoGenBaseFolder parentFolder) :
                    base("FlexObjectIceFish", "body/flexobject", parentFolder, 10000, false, "482e3a00-81cf-4ed7-a9f9-1a6074246482")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 10000, null, "482e3a00-81cf-4ed7-a9f9-1a6074246482");
                _buttonok1Info = new RepoItemInfo(this, "ButtonOK1", "container[@caption='Publish Process']/element[@type='AlertForm']/button[@text='OK']", 10000, null, "f831e0b2-004c-4a8d-9570-209fc2a5dc7c");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@caption='Save Process']/element[@type='AlertForm']/button[@text='OK']", 10000, null, "8a5f83fc-6080-4a01-95b0-f2d78f99e714");
                _textserviceid2Info = new RepoItemInfo(this, "TextServiceId2", "form/container/container[2]/container[2]/text[@id='serviceId']", 10000, null, "df66c625-b7f3-4c85-9e1c-16f6939a09c5");
                _textserviceid1Info = new RepoItemInfo(this, "TextServiceId1", "form/container/container[2]/container[3]/text[@id='serviceId']", 10000, null, "c1f0688f-dfa4-4ca6-9994-215886dfb6b7");
                _buttonload_template___Info = new RepoItemInfo(this, "ButtonLoad_template___", "form/element[@type='ControlBar']/button[@text='Load template...']", 10000, null, "134a4378-9c74-42d0-a640-8f74ece6fcc1");
                _buttonsaveInfo = new RepoItemInfo(this, "ButtonSave", "form/element[@type='ControlBar']/button[@text='Save']", 10000, null, "53f5f71b-7a92-4bcc-bbd8-48d52891ceb0");
                _textserviceidInfo = new RepoItemInfo(this, "TextServiceId", "form/form/container[10]/text[@id='ServiceId']", 10000, null, "5839e3e2-b9ed-4a82-9257-1091c4301e91");
                _buttonloadInfo = new RepoItemInfo(this, "ButtonLoad", "form[@title='Choose Template']/element[@type='ControlBar']/button[@text='Load']", 10000, null, "ea0ea167-9342-4739-ae08-8c2e95c16d15");
                _buttonbuttonInfo = new RepoItemInfo(this, "ButtonButton", "form[@title='Choose Template']/form/container/combobox/button[@type='Button']", 10000, null, "45f43ab6-8dfa-4a4a-a09c-d7fde8750b1c");
                _textdestinationfileInfo = new RepoItemInfo(this, "TextDestinationfile", "list/listitem[@text='Destinationfile']/text[@caption='Destinationfile']", 10000, null, "3fb3c58f-9bde-4677-a1a0-7f64e08f20ef");
                _textparserfileInfo = new RepoItemInfo(this, "TextParserfile", "list/listitem[@text='Parserfile']/text[@caption='Parserfile']", 10000, null, "b3fbc59a-58b7-447d-b2d7-281d433328de");
                _textsourcefileInfo = new RepoItemInfo(this, "TextSourcefile", "list/listitem[@text='Sourcefile']/text[@caption='Sourcefile']", 10000, null, "fc05ff46-2e34-4408-9df6-bad1aa43ba4c");
                _texttagformaterInfo = new RepoItemInfo(this, "TextTagFormater", "list/listitem[@text='TagFormater']/text[@caption='TagFormater']", 10000, null, "9abf69af-5a95-4b50-9a86-bcf51b5b9950");
                _texttempintegerInfo = new RepoItemInfo(this, "TextTempinteger", "list/listitem[@text='Tempinteger']/text[@caption='Tempinteger']", 10000, null, "3f17bb47-a183-4823-aa2d-5b97b2d2a439");
                _indicatorscrollthumbInfo = new RepoItemInfo(this, "IndicatorScrollThumb", "list/scrollbar/indicator[@type='ScrollThumb']", 10000, null, "19c30e1d-6e69-4682-a36b-2fa9729e2e82");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("482e3a00-81cf-4ed7-a9f9-1a6074246482")]
            public virtual Ranorex.FlexObject Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.FlexObject>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("482e3a00-81cf-4ed7-a9f9-1a6074246482")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK1 item.
            /// </summary>
            [RepositoryItem("f831e0b2-004c-4a8d-9570-209fc2a5dc7c")]
            public virtual Ranorex.Button ButtonOK1
            {
                get
                {
                    return _buttonok1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK1 item info.
            /// </summary>
            [RepositoryItemInfo("f831e0b2-004c-4a8d-9570-209fc2a5dc7c")]
            public virtual RepoItemInfo ButtonOK1Info
            {
                get
                {
                    return _buttonok1Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("8a5f83fc-6080-4a01-95b0-f2d78f99e714")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("8a5f83fc-6080-4a01-95b0-f2d78f99e714")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The TextServiceId2 item.
            /// </summary>
            [RepositoryItem("df66c625-b7f3-4c85-9e1c-16f6939a09c5")]
            public virtual Ranorex.Text TextServiceId2
            {
                get
                {
                    return _textserviceid2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextServiceId2 item info.
            /// </summary>
            [RepositoryItemInfo("df66c625-b7f3-4c85-9e1c-16f6939a09c5")]
            public virtual RepoItemInfo TextServiceId2Info
            {
                get
                {
                    return _textserviceid2Info;
                }
            }

            /// <summary>
            /// The TextServiceId1 item.
            /// </summary>
            [RepositoryItem("c1f0688f-dfa4-4ca6-9994-215886dfb6b7")]
            public virtual Ranorex.Text TextServiceId1
            {
                get
                {
                    return _textserviceid1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextServiceId1 item info.
            /// </summary>
            [RepositoryItemInfo("c1f0688f-dfa4-4ca6-9994-215886dfb6b7")]
            public virtual RepoItemInfo TextServiceId1Info
            {
                get
                {
                    return _textserviceid1Info;
                }
            }

            /// <summary>
            /// The ButtonLoad_template___ item.
            /// </summary>
            [RepositoryItem("134a4378-9c74-42d0-a640-8f74ece6fcc1")]
            public virtual Ranorex.Button ButtonLoad_template___
            {
                get
                {
                    return _buttonload_template___Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonLoad_template___ item info.
            /// </summary>
            [RepositoryItemInfo("134a4378-9c74-42d0-a640-8f74ece6fcc1")]
            public virtual RepoItemInfo ButtonLoad_template___Info
            {
                get
                {
                    return _buttonload_template___Info;
                }
            }

            /// <summary>
            /// The ButtonSave item.
            /// </summary>
            [RepositoryItem("53f5f71b-7a92-4bcc-bbd8-48d52891ceb0")]
            public virtual Ranorex.Button ButtonSave
            {
                get
                {
                    return _buttonsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave item info.
            /// </summary>
            [RepositoryItemInfo("53f5f71b-7a92-4bcc-bbd8-48d52891ceb0")]
            public virtual RepoItemInfo ButtonSaveInfo
            {
                get
                {
                    return _buttonsaveInfo;
                }
            }

            /// <summary>
            /// The TextServiceId item.
            /// </summary>
            [RepositoryItem("5839e3e2-b9ed-4a82-9257-1091c4301e91")]
            public virtual Ranorex.Text TextServiceId
            {
                get
                {
                    return _textserviceidInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextServiceId item info.
            /// </summary>
            [RepositoryItemInfo("5839e3e2-b9ed-4a82-9257-1091c4301e91")]
            public virtual RepoItemInfo TextServiceIdInfo
            {
                get
                {
                    return _textserviceidInfo;
                }
            }

            /// <summary>
            /// The ButtonLoad item.
            /// </summary>
            [RepositoryItem("ea0ea167-9342-4739-ae08-8c2e95c16d15")]
            public virtual Ranorex.Button ButtonLoad
            {
                get
                {
                    return _buttonloadInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonLoad item info.
            /// </summary>
            [RepositoryItemInfo("ea0ea167-9342-4739-ae08-8c2e95c16d15")]
            public virtual RepoItemInfo ButtonLoadInfo
            {
                get
                {
                    return _buttonloadInfo;
                }
            }

            /// <summary>
            /// The ButtonButton item.
            /// </summary>
            [RepositoryItem("45f43ab6-8dfa-4a4a-a09c-d7fde8750b1c")]
            public virtual Ranorex.Button ButtonButton
            {
                get
                {
                    return _buttonbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonButton item info.
            /// </summary>
            [RepositoryItemInfo("45f43ab6-8dfa-4a4a-a09c-d7fde8750b1c")]
            public virtual RepoItemInfo ButtonButtonInfo
            {
                get
                {
                    return _buttonbuttonInfo;
                }
            }

            /// <summary>
            /// The TextDestinationfile item.
            /// </summary>
            [RepositoryItem("3fb3c58f-9bde-4677-a1a0-7f64e08f20ef")]
            public virtual Ranorex.Text TextDestinationfile
            {
                get
                {
                    return _textdestinationfileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextDestinationfile item info.
            /// </summary>
            [RepositoryItemInfo("3fb3c58f-9bde-4677-a1a0-7f64e08f20ef")]
            public virtual RepoItemInfo TextDestinationfileInfo
            {
                get
                {
                    return _textdestinationfileInfo;
                }
            }

            /// <summary>
            /// The TextParserfile item.
            /// </summary>
            [RepositoryItem("b3fbc59a-58b7-447d-b2d7-281d433328de")]
            public virtual Ranorex.Text TextParserfile
            {
                get
                {
                    return _textparserfileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextParserfile item info.
            /// </summary>
            [RepositoryItemInfo("b3fbc59a-58b7-447d-b2d7-281d433328de")]
            public virtual RepoItemInfo TextParserfileInfo
            {
                get
                {
                    return _textparserfileInfo;
                }
            }

            /// <summary>
            /// The TextSourcefile item.
            /// </summary>
            [RepositoryItem("fc05ff46-2e34-4408-9df6-bad1aa43ba4c")]
            public virtual Ranorex.Text TextSourcefile
            {
                get
                {
                    return _textsourcefileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextSourcefile item info.
            /// </summary>
            [RepositoryItemInfo("fc05ff46-2e34-4408-9df6-bad1aa43ba4c")]
            public virtual RepoItemInfo TextSourcefileInfo
            {
                get
                {
                    return _textsourcefileInfo;
                }
            }

            /// <summary>
            /// The TextTagFormater item.
            /// </summary>
            [RepositoryItem("9abf69af-5a95-4b50-9a86-bcf51b5b9950")]
            public virtual Ranorex.Text TextTagFormater
            {
                get
                {
                    return _texttagformaterInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextTagFormater item info.
            /// </summary>
            [RepositoryItemInfo("9abf69af-5a95-4b50-9a86-bcf51b5b9950")]
            public virtual RepoItemInfo TextTagFormaterInfo
            {
                get
                {
                    return _texttagformaterInfo;
                }
            }

            /// <summary>
            /// The TextTempinteger item.
            /// </summary>
            [RepositoryItem("3f17bb47-a183-4823-aa2d-5b97b2d2a439")]
            public virtual Ranorex.Text TextTempinteger
            {
                get
                {
                    return _texttempintegerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextTempinteger item info.
            /// </summary>
            [RepositoryItemInfo("3f17bb47-a183-4823-aa2d-5b97b2d2a439")]
            public virtual RepoItemInfo TextTempintegerInfo
            {
                get
                {
                    return _texttempintegerInfo;
                }
            }

            /// <summary>
            /// The IndicatorScrollThumb item.
            /// </summary>
            [RepositoryItem("19c30e1d-6e69-4682-a36b-2fa9729e2e82")]
            public virtual Ranorex.Indicator IndicatorScrollThumb
            {
                get
                {
                    return _indicatorscrollthumbInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The IndicatorScrollThumb item info.
            /// </summary>
            [RepositoryItemInfo("19c30e1d-6e69-4682-a36b-2fa9729e2e82")]
            public virtual RepoItemInfo IndicatorScrollThumbInfo
            {
                get
                {
                    return _indicatorscrollthumbInfo;
                }
            }
        }

        /// <summary>
        /// The ContextMenuIexploreAppFolder folder.
        /// </summary>
        [RepositoryFolder("7da7aa1b-b388-422c-a1e7-c246daf28d41")]
        public partial class ContextMenuIexploreAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _menuitemconfigure_componentInfo;

            /// <summary>
            /// Creates a new ContextMenuIexplore  folder.
            /// </summary>
            public ContextMenuIexploreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContextMenuIexplore", "/contextmenu[@processname='iexplore']", parentFolder, 30000, true, "7da7aa1b-b388-422c-a1e7-c246daf28d41")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 30000, null, "7da7aa1b-b388-422c-a1e7-c246daf28d41");
                _menuitemconfigure_componentInfo = new RepoItemInfo(this, "MenuItemConfigure_Component", "contextmenu/menuitem[@accessiblename='Configure Component']", 10000, null, "feb24880-6117-4b08-99c8-6a68eec8ee73");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7da7aa1b-b388-422c-a1e7-c246daf28d41")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7da7aa1b-b388-422c-a1e7-c246daf28d41")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemConfigure_Component item.
            /// </summary>
            [RepositoryItem("feb24880-6117-4b08-99c8-6a68eec8ee73")]
            public virtual Ranorex.MenuItem MenuItemConfigure_Component
            {
                get
                {
                    return _menuitemconfigure_componentInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemConfigure_Component item info.
            /// </summary>
            [RepositoryItemInfo("feb24880-6117-4b08-99c8-6a68eec8ee73")]
            public virtual RepoItemInfo MenuItemConfigure_ComponentInfo
            {
                get
                {
                    return _menuitemconfigure_componentInfo;
                }
            }
        }

    }
}
