//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.03 at 03:05:55 PM EST 
//


package com.tfp.properties;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDSConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDSConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBConnection" type="{}DBConnectionConfigType"/>
 *         &lt;element name="Defaults" type="{}TDSDefaultsConfigType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDSConfigType", propOrder = {
    "dbConnection",
    "defaults"
})
public class TDSConfigType {

    @XmlElement(name = "DBConnection", required = true)
    protected DBConnectionConfigType dbConnection;
    @XmlElement(name = "Defaults")
    protected TDSDefaultsConfigType defaults;

    /**
     * Gets the value of the dbConnection property.
     * 
     * @return
     *     possible object is
     *     {@link DBConnectionConfigType }
     *     
     */
    public DBConnectionConfigType getDBConnection() {
        return dbConnection;
    }

    /**
     * Sets the value of the dbConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBConnectionConfigType }
     *     
     */
    public void setDBConnection(DBConnectionConfigType value) {
        this.dbConnection = value;
    }

    /**
     * Gets the value of the defaults property.
     * 
     * @return
     *     possible object is
     *     {@link TDSDefaultsConfigType }
     *     
     */
    public TDSDefaultsConfigType getDefaults() {
        return defaults;
    }

    /**
     * Sets the value of the defaults property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDSDefaultsConfigType }
     *     
     */
    public void setDefaults(TDSDefaultsConfigType value) {
        this.defaults = value;
    }

}
